### ISSUE TITLE
[Bug] Parsing an emtpy dictionary as fixed_features to optimize_acqf

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1027]
# 🐛 Bug

I would expect that parsing an empty dictionary as `fixed_features`  in `optimize_acqf` would result in the same as parsing `None`. But the empty dictionary results in an error. Fixing it should be easy. Just add the line 

```python
if len(fixed_features)==0: REDUCED=False
```
at line 92 of `gen.py`  (https://github.com/pytorch/botorch/blob/main/botorch/generation/gen.py#L92)

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.acquisition import UpperConfidenceBound
from botorch.optim import optimize_acqf

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_model(mll)

UCB = UpperConfidenceBound(gp, beta=0.1)

bounds = torch.stack([torch.zeros(2), torch.ones(2)])
candidate, acq_value = optimize_acqf(
    UCB, bounds=bounds, q=1, num_restarts=5, raw_samples=20,fixed_features={}
)
print(candidate)
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "mwe.py", line 22, in <module>
    UCB, bounds=bounds, q=1, num_restarts=5, raw_samples=20,fixed_features={}
  File "C:\ProgramData\Anaconda3\envs\aichembuddy2\lib\site-packages\botorch\optim\optimize.py", line 210, in optimize_acqf
    fixed_features=fixed_features,
  File "C:\ProgramData\Anaconda3\envs\aichembuddy2\lib\site-packages\botorch\generation\gen.py", line 104, in gen_candidates_scipy
    equality_constraints=equality_constraints,
  File "C:\ProgramData\Anaconda3\envs\aichembuddy2\lib\site-packages\botorch\generation\utils.py", line 120, in _remove_fixed_features_from_optimization
    values=sorted_values,
  File "C:\ProgramData\Anaconda3\envs\aichembuddy2\lib\site-packages\botorch\acquisition\fixed_feature.py", line 99, in __init__
    new_values = torch.cat(torch.broadcast_tensors(*new_values), dim=-1)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\RegisterCPU.cpp:16286 [kernel]
CUDA: registered at aten\src\ATen\RegisterCUDA.cpp:20674 [kernel]
QuantizedCPU: registered at aten\src\ATen\RegisterQuantizedCPU.cpp:1025 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradCPU: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradCUDA: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradXLA: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradMLC: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradHPU: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradNestedTensor: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse1: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse2: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse3: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:9928 [autograd kernel]
Tracer: registered at ..\torch\csrc\autograd\generated\TraceType_2.cpp:9621 [kernel]
Autocast: registered at ..\aten\src\ATen\autocast_mode.cpp:259 [kernel]
Batched: registered at ..\aten\src\ATen\BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
```

## Expected Behavior

I would expect the same behavior as parsing `None` as `fixed_features`.

## System information

- botorch: 0.6.0
- gyptorch: 1.6.0
- pytorch: 1.9.1
- OS: Windows

**Comment by Balandat** [comment]
Thanks for flagging, PR is up.
