### ISSUE TITLE
[Feature Request]  `HeteroskedasticSingleTaskGP` model with `qKG` acquisition function

### ISSUE THREAD

**Issue by sambitmishra98** [pytorch/botorch#1393]
I am getting a NotImplementedError when trying to use `HeteroskedasticSingleTaskGP` model with `qKG` acquisition function. I am guessing the implementation of the two has not been worked out yet, since I was able to use `SingleTaskGP` with `qKG` and `HeteroskedasticSingleTaskGP` with `qNEI`. Is there a way to go around this issue? Also can this feature be added?

```
from botorch.fit              import fit_gpytorch_model as fit_model
import numpy as np

from botorch.acquisition.objective import ScalarizedPosteriorTransform
from botorch.optim.optimize   import optimize_acqf

from torch import autograd


class optim_handler:
    """
        Handle for converging to a model based on given dataset and bounds. 
        
    """
    import torch

    from botorch.models           import SingleTaskGP, HeteroskedasticSingleTaskGP
    from botorch.models.transforms import Normalize, Standardize 
    from gpytorch.mlls            import ExactMarginalLogLikelihood

    torch.random.manual_seed(0)
    torch_kwargs = {'dtype': torch.float32, 'device': torch.device("cpu")}

    def __init__(self, dataset:np.ndarray, bounds:np.ndarray):

        self.X     = self.torch.tensor(dataset[:,  :-2]   , **self.torch_kwargs)
        self.Y     = self.torch.tensor(dataset[:,-2:-1]   , **self.torch_kwargs)
        self.Y_std = self.torch.tensor(dataset[:,-1:  ]   , **self.torch_kwargs)
        self.Y_var = self.Y_std**2
        self.Y_err = 1.96 * self.Y_std/self.Y
        self.bnds  = self.torch.tensor(bounds             , **self.torch_kwargs)
        
        self.model_kwargs ={'train_X': self.X, 
                            'train_Y': self.Y,
                            'outcome_transform': self.Standardize(m=1),
                            'input_transform': self.Normalize(d=self.X.shape[-1], bounds = self.bnds)
                            }

    def show_opt_output(self) -> None:
        """ Print the end result of optimisation
        """
        print("----------------------------------------------")
        print(f"{len(self.X_cand)} candidate(s) generated.") 

        if len(self.X_cand) == 1 :
            print(f"Next suggested candidate is {self.X_cand.tolist()}")
            Y_cand = self.mean_from_model()
            print(f"Next simulation's cost may be around {Y_cand}.")

    def conf_from_model(self):

        posterior = self.model.posterior(self.X_cand)
        lower, upper = posterior.mvn.confidence_region()
        l = self.unstandardise_Y(lower)
        m = self.unstandardise_Y(self.model(self.X_cand)[0].mean)
        u = self.unstandardise_Y(upper)
        
        return l, m, u

    def mean_from_model(self):
        return self.unstandardise_Y(self.model(self.X_cand)[0].mean)

    def std_from_model(self):
        return self.unstandardise_Y(self.model(self.X_cand)[0].std)

    def calc_from_model(self, X_cand:list):

        X_cand_tensor = self.torch.tensor(X_cand)

        if X_cand_tensor.dim() == 1:
            X_cand_tensor = X_cand_tensor.reshape(1,-1)   
            
        posterior = self.model.posterior(X_cand_tensor)
        mn = self.unstandardise_Y(posterior.mean)
        print(f'Given: {X_cand_tensor}, posterior mean: {mn}')
        return mn

    def compare_wallt(self, opt_list:list) -> None:
        """Compare the actual simulation wall-time with prediction

        Args:
            wallt_a (list): Actual wall-time
        """
        
        print('_____________________________________________________________________________________')
        print(f"{'Candidate':<30}   {'Predicted':>11}   {'Actual':>11}   {'Error':>11}")

        err_cands  = [opt_val[:-1] for opt_val in opt_list]
        err_wtimes = [opt_val[-1]  for opt_val in opt_list]

        Err = []

        for i, _ in enumerate(opt_list) :
            X_cand = self.torch.tensor(err_cands[i:i+1])

            posterior = self.model.posterior(X_cand)
            #Y_cand_st = posterior.mean.tolist()[0][0]
            #Y_cand = self.unstandardise_Y(-Y_cand_st)

            Y_cand = self.unstandardise_Y(self.model(X_cand).mean)
            Err.append(abs((err_wtimes[i] - Y_cand)/err_wtimes[i]))
            print(*[f"{ii}" for ii in err_cands[i]], 
                  f"--> {Y_cand:>10.3f}  {err_wtimes[i]:>10.3f}  {Err[i]*100:>10.3f} %")
        print('_____________________________________________________________________________________')

        return Err

    def calc_wallt(self, opt_list:list) -> None:
        """Compare the actual simulation wall-time with prediction

        Args:
            wallt_a (list): Actual wall-time
        """

        print(f"{'Candidate':<30}{'Predicted':>11}{'Actual':>11}{'Error':>11}")

        err_cands  = [opt_val[:-1] for opt_val in opt_list]

        Err = []

        for i, _ in enumerate(opt_list) :
            X_cand = self.torch.tensor(err_cands[i:i+1])
            Y_cand = self.unstandardise_Y(self.model(X_cand).mean)
        return 



class optimiser(optim_handler):
    """
        Explores the solution space with Bayesian Optimisation.
        This would be expensive, but worth it in the long run.
    """
 
    def __init__(self, dataset:np.ndarray, bounds:np.ndarray) -> None:
        super().__init__(dataset, bounds)

    def __optimise_now(self, raw_samples = 512, num_restarts = 10):
        self.X_cand, _ = optimize_acqf(
            acq_function = self.__acquisition_function, 
            bounds       = self.bnds,
            q            = 1,
            num_restarts = num_restarts,
            raw_samples  = raw_samples,
        )
        return self.X_cand.tolist()[0]

    def exploreqKG(self):
        from botorch.acquisition import qKnowledgeGradient as qKG

        model1 = self.HeteroskedasticSingleTaskGP(train_Yvar = self.Y_var, **self.model_kwargs)
        mll1 = self.ExactMarginalLogLikelihood(likelihood=model1.likelihood, 
                                              model=model1, 
                                              )
        mll1 = mll1.to(self.X)
        fit_model(mll1)

        self.__acquisition_function = qKG(model1, num_fantasies = 64,
                               posterior_transform = ScalarizedPosteriorTransform(weights=self.torch.tensor([-1.0])),)
        return self.__optimise_now(raw_samples = 512, num_restarts = 10)

    def exploreqNEI(self):
        from botorch.acquisition import qNoisyExpectedImprovement as qNEI
        #print("Exploration starts with ExpectedImprovement Bayesian Optimisation")    
        model2 = self.HeteroskedasticSingleTaskGP(train_Yvar = self.Y_var, **self.model_kwargs)
        mll2 = self.ExactMarginalLogLikelihood(likelihood=model2.likelihood, model=model2, )
        mll2 = mll2.to(self.X)
        fit_model(mll2)

        self.__acquisition_function = qNEI(model2, self.X,
            posterior_transform = ScalarizedPosteriorTransform(weights=self.torch.tensor([-1.0])),)
        return self.__optimise_now(raw_samples = 1024, num_restarts = 100)

    def evaluatePM(self):
        """Get the minimum from posterior mean."""

        from botorch.acquisition import PosteriorMean as PM

        model3 = self.HeteroskedasticSingleTaskGP(train_Yvar = self.Y_var, **self.model_kwargs)
        mll3 = self.ExactMarginalLogLikelihood(likelihood=model3.likelihood, model=model3, )
        mll3 = mll3.to(self.X)
        fit_model(mll3)

        self.__acquisition_function = PM(model3, maximize = False)

        return self.__optimise_now(raw_samples = 1024, num_restarts = 100)

    def evaluateLOOCV(self):
        """Get quality of model"""

        from botorch.cross_validation import gen_loo_cv_folds, batch_cross_validation

        if self.X.shape[0] %2==0:
            cv_folds = gen_loo_cv_folds(train_X    = self.X, 
                                        train_Y    = self.Y, 
                                    )
        else:
            cv_folds = gen_loo_cv_folds(train_X    = self.X, 
                                        train_Y    = self.Y, 
                                        train_Yvar = self.Y_var
                                    )


        cv_results = batch_cross_validation( 
                    model_cls = self.HeteroskedasticSingleTaskGP, 
                    mll_cls   = self.ExactMarginalLogLikelihood, 
                    cv_folds  = cv_folds,)

        posterior = cv_results.posterior
        mean = posterior.mean
        cv_error = ((cv_folds.test_Y.squeeze() - mean.squeeze()) ** 2).mean()
        print(f"Cross-validation error: {cv_error : 4.2}")

        lower, upper = posterior.mvn.confidence_region()

        from matplotlib import pyplot as plt

        _, axes = plt.subplots(1, 1, figsize=(6, 4))
        plt.plot([0, 4], [0, max(self.Y)], 'k', label="true objective", linewidth=2)

        axes.set_xlabel("Actual")
        axes.set_ylabel("Predicted")

        axes.errorbar(
            x=cv_folds.test_Y.numpy().flatten(), 
            y=mean.numpy().flatten(), 
            xerr=self.Y_err.numpy().flatten(),
            yerr=((upper-lower)/2).numpy().flatten(),
            fmt='*'
        )

        plt.savefig(f"loocv_plots/LOOCV-{np.shape(self.X)[0]}.png")

        try:
            return cv_error.detach().numpy()
        except:
            return 0


if __name__ == "__main__":

    opt_hist = np.array([       
[1.0	     ,5.32	 ,8.62	 ,1.0	 ,3.469931521995022	 ,0.15084671996718488],
[1.01	 ,3.508	 ,1.056	 ,4.44	 ,3.0313060119951842	 ,0.142843038037407],
[1.056	 ,1.375	 ,1.211	 ,5.88	 ,3.284004883604939	 ,0.08974095246203823],
[1.03	 ,5.113	 ,2.611	 ,4.758	 ,2.7276665300043534	 ,0.06864569117860327],
[1.14	 ,6.883	 ,1.689	 ,4.164	 ,2.653645221333136	 ,0.08835833306039219],
[0.9976	 ,7.305	 ,1.924	 ,6.176	 ,2.835054016664799	 ,0.12341695957709688],
[2.512	 ,6.984	 ,2.723	 ,3.625	 ,2.401715438000489	 ,0.0501839288853536],
[3.645	 ,6.582	 ,2.12	 ,3.916	 ,2.4657301871380435	 ,0.13502478920112984],
[3.227	 ,7.69	 ,2.416	 ,1.956	 ,2.6161442657238303	 ,0.134975290605758],
[3.455	 ,8.05	 ,3.248	 ,4.383	 ,2.4362339208601043	 ,0.0763049692881096],
[3.627	 ,6.414	 ,3.662	 ,3.818	 ,2.3531628668632556	 ,0.08959766019903548],
[3.309	 ,6.297	 ,3.799	 ,4.758	 ,2.4697823554285736	 ,0.09684451240582466],
[5.383	 ,6.723	 ,3.621	 ,3.646	 ,2.4180864102454507	 ,0.0949956524836544],
[3.098	 ,7.285	 ,4.28	 ,3.402	 ,2.417899090261926	 ,0.07452566623072517],
[3.645	 ,5.742	 ,3.56	 ,3.17	 ,2.3491518319982183	 ,0.06494949029839713],
[4.41	 ,5.254	 ,4.117	 ,3.371	 ,2.479834037103703	 ,0.059859927823423295],
[2.334	 ,6.05	 ,3.65	 ,3.01	 ,2.4447961137807903	 ,0.0952101333908594],
[4.15	 ,6.938	 ,3.514	 ,2.81	 ,2.425653966004029	 ,0.07915923263163083],
[4.254	 ,5.53	 ,2.812	 ,3.389	 ,2.4762093682031265	 ,0.1247154004151244],
[10.0	 ,10.0	 ,5.09	 ,6.2	 ,26.550974283993128	 ,4.411758691127266],
[0.787	 ,10.0	 ,10.0	 ,8.08	 ,2.957984932732705	 ,0.43974607928385256],
[0.787	 ,1.191	 ,10.0	 ,9.79	 ,2.625034426000308	 ,0.07595628151917394],
[2.25	 ,1.0	 ,10.0	 ,5.99	 ,2.5538451341814254	 ,0.08654861916579396],
[2.203	 ,5.703	 ,10.0	 ,10.0	 ,2.5229998036678203	 ,0.08632527748001667],
[1.374	 ,4.703	 ,10.03	 ,7.11	 ,2.5520782235010606	 ,0.08713511252325115],
[4.35	 ,10.0	 ,10.45	 ,6.938	 ,2.391843813383065	 ,0.07045647178219852],
[4.867	 ,10.0	 ,4.766	 ,7.332	 ,11.966253685816561	 ,10.439736072377116],
[3.234	 ,9.17	 ,10.484	 ,4.555	 ,3.464793102767614	 ,0.5222274546485405],
[3.797	 ,1.0	 ,10.59	 ,8.49	 ,2.4228520332264734	 ,0.05644599637011874],
[1.983	 ,1.0	 ,6.508	 ,8.58	 ,2.721301035077956	 ,0.09255794329238595],
[3.29	 ,7.184	 ,11.69	 ,7.83	 ,2.4954472866207094	 ,0.14119999778021255],
[0.2477	 ,7.355	 ,5.285	 ,10.0	 ,2.7430776664301186	 ,0.07533276864832991],
[3.525	 ,5.523	 ,8.7	 ,6.88	 ,3.165797036000835	 ,0.3286117704763439],
[0.2477	 ,1.0	 ,11.69	 ,4.13	 ,2.5718734331406137	 ,0.11303499993632911],
[0.2404	 ,0.76	 ,7.72	 ,5.926	 ,2.7799387269988074	 ,0.12337728364566593],
[4.25	 ,0.76	 ,11.414	 ,1.0	 ,4.863054728004499	 ,0.21629626567292387],
#[1.0	    ,2.0	     ,2.0	 ,2.0	 ,3.1270113454957027	 ,0.5413061233313805],
#[ 1.        ,  2.        ,  2.        ,  2.        ,  3.080895  ,        0.48222797]
])

    
    bounds = np.array([[ 0.9326,  1.,  1.,  1.],
                       [10., 10., 10.195, 10.]])
    
    cand_as_list = optimiser(opt_hist, bounds).exploreqKG()
    print(cand_as_list)
```
The following is the error I get:
```
Traceback (most recent call last):
  File "/home/sambit98/pyfr-installation/PyFR/optimiser/optimiser/optimisables_handler.py", line 286, in <module>
    cand_as_list = optimiser(opt_hist, bounds).exploreqKG()
  File "/home/sambit98/pyfr-installation/PyFR/optimiser/optimiser/optimisables_handler.py", line 159, in exploreqKG
    return self.__optimise_now(raw_samples = 512, num_restarts = 10)
  File "/home/sambit98/pyfr-installation/PyFR/optimiser/optimiser/optimisables_handler.py", line 138, in __optimise_now
    self.X_cand, _ = optimize_acqf(
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/optim/optimize.py", line 230, in optimize_acqf
    batch_initial_conditions = _gen_initial_conditions()
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/optim/optimize.py", line 216, in _gen_initial_conditions
    batch_initial_conditions = ic_gen(
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/optim/initializers.py", line 291, in gen_one_shot_kg_initial_conditions
    ics = gen_batch_initial_conditions(
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/optim/initializers.py", line 194, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/utils/transforms.py", line 258, in decorated
    output = method(acqf, X, *args, **kwargs)
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/acquisition/knowledge_gradient.py", line 196, in forward
    fantasy_model = self.model.fantasize(
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/models/model.py", line 173, in fantasize
    return self.condition_on_observations(
  File "/home/sambit98/pyfr-installation/pyfr-venv/lib/python3.10/site-packages/botorch/models/gp_regression.py", line 438, in condition_on_observations
    raise NotImplementedError
NotImplementedError
```

**Comment by saitcakmak** [comment]
This has been requested in #936. There is some discussion in there on why this hasn't been implemented. Tl;DR is that it is tricky to fantasize on the noise model.

**Comment by sambitmishra98** [comment]
Given that I do have the noise level at every datapoint and I wish to use qKG, I think I have two options now: use SingleTaskGP or FixedNoiseGP with a mean noise value. Which of these would be better?

**Comment by saitcakmak** [comment]
We prefer `FixedNoiseGP` when the noise level is known.
