### ISSUE TITLE
[Bug] Inconsistent behavior of `subset_output` with `BatchedMultiOutputGPyTorchModel`, `ModelListGP`, `ModelList`

### ISSUE THREAD

**Issue by esantorella** [pytorch/botorch#1550]
# 🐛 Bug

* [`BatchedMultiOutputGPyTorchModel.subset_output`](https://github.com/pytorch/botorch/blob/2437241e11a7ede25e7b11d1be9d0bc6d955a421/botorch/models/gpytorch.py#L482) indexes into the -3 (batch) dimension of the data, and errors if the data is not at least 3d. This also goes for subclasses like `SingleTaskGP`.
* `ModelListGP.subset_output` indexes into the list of models, which corresponds to the -2 (output) dimension of the data, so it does run with batched data.
*  [`ModelList.subset_output`](https://github.com/pytorch/botorch/blob/2437241e11a7ede25e7b11d1be9d0bc6d955a421/botorch/models/model.py#L456) calls `subset_output` on its component models, so if one of those components is a `BatchedMultiOutputGPyTorchModel` it will also error.
* Even when the methods do run, inconsistency about which dimension is being indexed leads to `SingleTaskGP`, `ModelListGP`, and `ModelList` all giving different results (in both numerics and shape) with subset_output

## Issue 1: With unbatched data, `SingleTaskGP.subset_output` and `ModelList.subset_output` error, but `ModelListGP.subset_output` doesn't

This is an issue for fixing #1519, where we will recommend replace a `ModelListGP` with a `ModelList` in some cases. In code like the example below, that replacement would raise an error.

Example:

```python
import torch
from botorch.models import SingleTaskGP, ModelListGP, ModelList

train_X = torch.tensor([[0], [1]], dtype=torch.float64)  # shape (2, 1). n=2, d=1, batch_shape = (,)
train_Y = torch.tensor([[2], [3]], dtype=torch.float64)  # shape (2, 1). n=2, m=1, batch_shape = (,)
single_task = SingleTaskGP(train_X, train_Y)

#  produces the below error
single_task.subset_output([0]
```

```
Traceback (most recent call last):
  File "/Users/santorella/repos/botorch/scratch.py", line 16, in <module>
    single_task.subset_output([0])
  File "/Users/santorella/repos/botorch/botorch/models/gpytorch.py", line 481, in subset_output
    new_model.train_inputs = tuple(
  File "/Users/santorella/repos/botorch/botorch/models/gpytorch.py", line 482, in <genexpr>
    ti[..., idxr, :, :] for ti in new_model.train_inputs
IndexError: too many indices for tensor of dimension 2
```

It does work as part of a `ModelListGP`, and there are existing use cases that look like this:

```python
model_list_gp = ModelListGP(single_task)
result = model_list_gp.subset_output([0])
print(type(result))  # ModelListGP
print(result.train_inputs)  # [(tensor([[0.], [1.]], dtype=torch.float64),)]
```

It doesn't work as part of a ModelList:

```python
ModelList(single_task).subset_output([0])
```

Error:
```
Traceback (most recent call last):
  File "/Users/santorella/repos/botorch/scratch.py", line 18, in <module>
    ModelList(single_task).subset_output([0])
  File "/Users/santorella/repos/botorch/botorch/models/model.py", line 476, in subset_output
    subset_models = [
  File "/Users/santorella/repos/botorch/botorch/models/model.py", line 477, in <listcomp>
    deepcopy(self.models[grp_idx].subset_output(idcs=sub_idcs))
  File "/Users/santorella/repos/botorch/botorch/models/gpytorch.py", line 481, in subset_output
    new_model.train_inputs = tuple(
  File "/Users/santorella/repos/botorch/botorch/models/gpytorch.py", line 482, in <genexpr>
    ti[..., idxr, :, :] for ti in new_model.train_inputs
IndexError: too many indices for tensor of dimension 2
```
## Issue 2: With fewer outputs than batch dimensions, `ModelListGP.subset_output` may error where `ModelList.subset_output` and `SingleTaskGP.subset_output` do not.

In the below example, batch_dim=3 and there is only one model. Subsetting with `idcs=[1]` works for `SingleTaskGP` since the batch dimension is large enough. It runs for `ModelList` but surprisingly returns different numerical values. However, it doesn't work for `ModelListGP` since that looks for model #1, and there isn't one (only #0).

```python
train_X = torch.arange(12, dtype=torch.float64).reshape(3, 4, 1)
train_Y = torch.arange(12, dtype=torch.float64).reshape(3, 4, 1)
single_task = SingleTaskGP(train_X, train_Y) 
idcs = [1]

single_task_subsetted = single_task.subset_output(idcs)
# data contains 4, 5, 6, 7
print(single_task_subsetted.train_inputs)
# [torch.Size([4, 1])]
print([elt.shape for elt in single_task_subsetted.train_inputs])

model_list_subsetted = ModelList(single_task).subset_output(idcs)
# data contains 0, 1, 2, 3
print(model_list_subsetted.train_inputs)
# [[torch.Size([1]), torch.Size([1]), torch.Size([1]), torch.Size([1])]]
print([[t.shape for t in elt] for elt in model_list_subsetted.train_inputs])

# errors because there is no model 1
ModelListGP(single_task).subset_output(idcs)
```

```
Traceback (most recent call last):
  File "/Users/santorella/repos/botorch/scratch_batched.py", line 21, in <module>
    gp_list_subsetted = ModelListGP(single_task).subset_output(idcs)
  File "/Users/santorella/repos/botorch/botorch/models/model_list_gp_regression.py", line 119, in subset_output
    return self.__class__(*[deepcopy(self.models[i]) for i in idcs])
  File "/Users/santorella/repos/botorch/botorch/models/model_list_gp_regression.py", line 119, in <listcomp>
    return self.__class__(*[deepcopy(self.models[i]) for i in idcs])
  File "/Users/santorella/opt/anaconda3/envs/botorchdev/lib/python3.10/site-packages/torch/nn/modules/container.py", line 282, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/Users/santorella/opt/anaconda3/envs/botorchdev/lib/python3.10/site-packages/torch/nn/modules/container.py", line 272, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 1 is out of range
```

## Issue 3: Inconsistent behavior of `ModelListGP.subset_output`  and `ModelList.subset_output` even when they do run

In the below example `ModelListGP` and `ModelList` behave differently. For an example of `SingleTaskGP` and `ModelList` behaving differently, see above.

```
idcs = [0]

model_list_subsetted = ModelList(single_task).subset_output(idcs)
# data contains 0, 1, 2, 3
print(model_list_subsetted.train_inputs)

gp_list_subsetted = ModelListGP(single_task).subset_output(idcs)
# data contains 0, 1, ..., 11
print(gp_list_subsetted.train_inputs)
```

## Expected Behavior

* I would have expected `BatchedMultiOutputGPyTorchModel.subset_output` to act on the -2 dimension of the data, not -3, since it should be subsetting outputs, not batches.
* If I am wrong about the above, then `SingleTaskGP.subset_output` and other subclasses of `BatchedMultiOutputGPyTorchModel` should error when initialized with data of the wrong shape, and [docstrings that imply that unbatched data is okay](https://github.com/pytorch/botorch/blob/2437241e11a7ede25e7b11d1be9d0bc6d955a421/botorch/models/gp_regression.py#L84) should be changed.
* `subset_indices` should work similarly for `ModelListGP`, `ModelList`, and `SingleTaskGP`, producing models with the same `train_inputs`. The `train_inputs` could conceivably be structured differently but shouldn't contain different numbers.

## System information

**Please complete the following information:**
-  0.7.4.dev19+g9f55da2b
-  1.9.1.dev35+gc35d094a
-  1.13.0
-  MacOS

**Comment by esantorella** [comment]
Closing since the question is a bit confused and misleading. I still think there is some odd and under-documented behavior here and hope to refine this question, but as is it isn't helpful.
