### ISSUE TITLE
[Bug] Batch shape missing in TransformedPosterior

### ISSUE THREAD

**Issue by roussel-ryan** [pytorch/botorch#1623]
# 🐛 Bug

I'm getting an error when using Bilog, Power transformations (which return TransformedPosterior objects) with qNoisyExpectedHypervolumeImprovement. Works fine with transforms that return GPyTorchPosterior objects.

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.acquisition.multi_objective import qNoisyExpectedHypervolumeImprovement
from botorch.models import SingleTaskGP, ModelList
from botorch.fit import fit_gpytorch_mll
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.models.transforms.outcome import Bilog, Standardize, Log

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

standard_transform = Standardize(m=1)
bilog_transform = Bilog()

# try each transform
for transform in [standard_transform, bilog_transform]:
    gp = SingleTaskGP(train_X, train_Y, outcome_transform=transform)
    mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
    fit_gpytorch_mll(mll)

    ml = ModelList(gp,gp)

    acq = qNoisyExpectedHypervolumeImprovement(
        model=ml,
        X_baseline=train_X,
        cache_root=False,
        ref_point=torch.zeros(2)
    )

    test_x = torch.rand(10,1,2)
    print(f"{transform}: {acq(test_x)}")
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "C:\Users\Ryan Roussel\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch_19.py", line 26, in <module>
    acq = qNoisyExpectedHypervolumeImprovement(
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py", line 515, in __init__
    self._set_cell_bounds(num_new_points=X_baseline.shape[0])
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py", line 572, in _set_cell_bounds
    self._set_sampler(q_in=num_new_points * n_w, posterior=posterior)
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\acquisition\cached_cholesky.py", line 159, in _set_sampler
    self.sampler._update_base_samples(
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\sampling\list_sampler.py", line 68, in _update_base_samples
    s._update_base_samples(posterior=p, base_sampler=bs)
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\sampling\normal.py", line 116, in _update_base_samples
    len(posterior.base_sample_shape) - len(posterior.batch_shape)
AttributeError: 'TransformedPosterior' object has no attribute 'batch_shape'

```

## Expected Behavior

Successful evaluation of acquisition function

## System information

**Please complete the following information:**
- Botorch 0.8.1
- GPyTorch 1.9.1
- Pytorch 1.12.1
- Windows

**Comment by saitcakmak** [comment]
This should be using the batch shape of the underlying posterior. I'll put up a fix in a bit.

**Comment by roussel-ryan** [comment]
Great! There might be a related shape issue when using a ModuleListGP and a custom ListSampler, use this code to reproduce
```
import torch
from botorch.acquisition.multi_objective import qNoisyExpectedHypervolumeImprovement
from botorch.fit import fit_gpytorch_mll
from botorch.models import ModelList, SingleTaskGP
from botorch.models.transforms.input import Normalize
from botorch.models.transforms.outcome import Bilog, Log, Power, Standardize
from botorch.sampling import ListSampler, SobolQMCNormalSampler
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

train_X = torch.rand(10, 2)
Y = 1 - torch.norm(train_X - 0.5, dim=-1, keepdim=True)
Y = Y + 0.1 * torch.randn_like(Y)  # add some noise
train_Y = standardize(Y)

imput_normalize = Normalize(d=2)
standard_transform = Standardize(m=1)

# define ref point
ref = torch.zeros(2)

# try each transform
for transform in [standard_transform]:
    gp = SingleTaskGP(
        train_X, train_Y, input_transform=imput_normalize, outcome_transform=transform
    )
    mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
    fit_gpytorch_mll(mll)

    ml = ModelList(gp, gp)

    sampler = ListSampler(
        *[
            SobolQMCNormalSampler(sample_shape=128)
            for _ in range(ml.num_outputs)
        ]
    )

    acq = qNoisyExpectedHypervolumeImprovement(
        model=ml,
        ref_point=ref,
        X_baseline=torch.tensor([]).reshape(0, 2),
        sampler=sampler,
        cache_root=False,
    )

    test_x = torch.rand(10, 1, 2)
    print(f"{transform}: {acq(test_x)}")
```

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\Ryan Roussel\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch_19.py", line 44, in <module>
    acq = qNoisyExpectedHypervolumeImprovement(
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py", line 515, in __init__
    self._set_cell_bounds(num_new_points=X_baseline.shape[0])
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\botorch\acquisition\multi_objective\monte_carlo.py", line 587, in _set_cell_bounds
    self.sampler.sample_shape
  File "C:\ProgramData\Miniconda3\envs\xopt\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ListSampler' object has no attribute 'sample_shape'
```

I can open a separate issue if you'd like, but I didn't want to add to much to the issues queue

**Comment by saitcakmak** [comment]
Nice edge case. I'll put up a fix for that as well

**Comment by saitcakmak** [comment]
Closing this as both issues got fixed by the linked PRs
