### ISSUE TITLE
[Bug] `qNoisyExpectedHypervolumeImprovement` fails at single objective problem with uninformative error message

### ISSUE THREAD

**Issue by kstoneriv3** [pytorch/botorch#1880]
# 🐛 Bug

Hi, thanks for creating such a solid package for BO! It's really nice to be able to try various BO methods out of the box!! 

I have a minor bug report (or a request):

For m-objective Bayesian optimization, the `qNoisyExpectedHypervolumeImprovement` fails when m=1 while it works fine for m>1. 

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.acquisition.multi_objective import qNoisyExpectedHypervolumeImprovement
from botorch.models import SingleTaskGP

ref_point = [0.]
X_train = torch.randn(5, 2)
X_test = torch.randn(3, 2)
y_train = torch.randn(5, 1)  # 1-dimensional objective
model = SingleTaskGP(X_train, y_train)
qNEHVI = qNoisyExpectedHypervolumeImprovement(model, ref_point, X_test)
```

** Stack trace/error message **
```
(env_torch) kei@kei-Alienware-15-R4 ~/D/tmp (main)> python
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from botorch.acquisition.multi_objective import qNoisyExpectedHypervolumeImprovement
>>> from botorch.models import SingleTaskGP
>>> 
>>> ref_point = [0.]
>>> X_train = torch.randn(5, 2)
>>> X_test = torch.randn(3, 2)
>>> y_train = torch.randn(5, 1)  # 1-dimensional objective
>>> model = SingleTaskGP(X_train, y_train)
/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/models/gpytorch.py:129: UserWarning: The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444
  warnings.warn(_get_single_precision_warning(X.dtype), UserWarning)
/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)
/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/models/utils/assorted.py:201: InputDataWarning: Input data is not standardized. Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
>>> qNEHVI = qNoisyExpectedHypervolumeImprovement(model, ref_point, X_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 515, in __init__
    self._set_cell_bounds(num_new_points=X_baseline.shape[0])
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 632, in _set_cell_bounds
    self.partitioning = self.p_class(
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/utils/multi_objective/box_decompositions/non_dominated.py", line 384, in __init__
    super().__init__(ref_point=ref_point, Y=Y)
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/utils/multi_objective/box_decompositions/box_decomposition.py", line 274, in __init__
    super().__init__(ref_point=ref_point, Y=Y, sort=ref_point.shape[-1] == 2)
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/utils/multi_objective/box_decompositions/box_decomposition.py", line 67, in __init__
    self.partition_space()
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/utils/multi_objective/box_decompositions/box_decomposition.py", line 325, in partition_space
    super().partition_space()
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/utils/multi_objective/box_decompositions/box_decomposition.py", line 151, in partition_space
    self._partition_space()
  File "/home/kei/Desktop/env_torch/lib/python3.10/site-packages/botorch/utils/multi_objective/box_decompositions/box_decomposition.py", line 336, in _partition_space
    raise NotImplementedError(
NotImplementedError: _partition_space does not support batch dimensions.

```

## Expected Behavior

Ideally, when the number of objectives is one, it should work similarly to `qNoisyExpectedImprovement`, though it may be fine for this to fail as users are supposed to use  `qNoisyExpectedImprovement` in such a single objective case. However, even if it fails, I would like to see a more informative error message or assertion about the number of objectives.

## System information

**Please complete the following information:**
- BoTorch Version 0.8.5
- GPyTorch 1.10
- Pytorch 2.0.1+cu117
- 5.19.0-32-generic 22.04.1-Ubuntu

**Comment by Balandat** [comment]
Thanks for flagging this. I think it might be quite a bit of work to get this to work seamlessly for `m=1` for relatively little benefit. This kind of thing should be handled in some higher level API that abstracts away from the specific acquisition functions used under the hood. But I agree that this should raise an informative error.

**Comment by saitcakmak** [comment]
> This kind of thing should be handled in some higher level API that abstracts away from the specific acquisition functions used under the hood.

Something like [Ax](ax.dev)? :)

**Comment by kstoneriv3** [comment]
> Something like [Ax](https://github.com/pytorch/botorch/issues/ax.dev)? :)

I've been trying to use it in Optuna but they somehow support only `qNoisyExpectedHypervolumeImprovement` without supporting `qNoisyExpectedImprovement` right now. I will raise a PR there, as I am more comfortable with its codebase.

As for the error message on the BoTorch side, I can create a tiny PR  to add an assertion or to add ValueError at `qNoisyExpectedHypervolumeImprovement.__init__` if you are too busy to do it (i.e. if this issue is not closed for a while).

**Comment by Balandat** [comment]
> As for the error message on the BoTorch side, I can create a tiny PR to add an assertion or to add ValueError at qNoisyExpectedHypervolumeImprovement.__init__ if you are too busy to do it (i.e. if this issue is not closed for a while).

that would be great and much appreciated!
