### ISSUE TITLE
[Bug] `qMultiFidelityLowerBoundMaxValueEntropy` not working with fantasization

### ISSUE THREAD

**Issue by fjzzq2002** [pytorch/botorch#1978]
# 🐛 Bug

`qMultiFidelityLowerBoundMaxValueEntropy` seems to break with fantasization. The error seems specific to GIBBON as using `qMultiFidelityMaxValueEntropy` instead is fine.

## To reproduce

I defined a `SingleTaskMultiFidelityGP` model for a toy multi-fidelity task:

```python
import torch
from botorch.acquisition.max_value_entropy_search import (
    qMultiFidelityLowerBoundMaxValueEntropy,
    qMultiFidelityMaxValueEntropy,
)
from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskMultiFidelityGP
from botorch.optim import optimize_acqf_mixed
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.acquisition.utils import project_to_target_fidelity
train_X = torch.rand((10, 3), dtype=torch.double)
train_Y = torch.rand((10, 1), dtype=torch.double)
model = SingleTaskMultiFidelityGP(train_X, train_Y, data_fidelity=-1)
bounds = torch.tensor([[0.0] * 3, [1.0] * 3], dtype=torch.double)
```

When we evaluate its multi-fidelity GIBBON without fantasization, everything is working fine:

```python
candidate_set = torch.rand(100, bounds.size(1))
candidate_set = bounds[0] + (bounds[1] - bounds[0]) * candidate_set
MF_qGIBBON = qMultiFidelityLowerBoundMaxValueEntropy(model, candidate_set)
mf_gibbon = MF_qGIBBON(train_X[:1])
```

But when we fantasize it by setting `X_pending`, evaluation throws an error:

```python
pending_X = torch.rand((5, 3), dtype=torch.double)
MF_qGIBBON.set_X_pending(pending_X)
mf_gibbon = MF_qGIBBON(train_X[:1]) # ERROR!
```

**Stack trace/error message**

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    mf_gibbon = MF_qGIBBON(train_X[:1])
  File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "lib/python3.10/site-packages/botorch/utils/transforms.py", line 277, in decorated
    output = method(acqf, X, *args, **kwargs)
  File "lib/python3.10/site-packages/botorch/acquisition/max_value_entropy_search.py", line 809, in forward
    ig = self._compute_information_gain(
  File "lib/python3.10/site-packages/botorch/acquisition/max_value_entropy_search.py", line 861, in _compute_information_gain
    return qLowerBoundMaxValueEntropy._compute_information_gain(
  File "lib/python3.10/site-packages/botorch/acquisition/max_value_entropy_search.py", line 586, in _compute_information_gain
    normalized_mvs = (mvs - mean_m) / stdv
RuntimeError: The size of tensor a (10) must match the size of tensor b (16) at non-singleton dimension 1
```
## Expected Behavior

Evaluation runs through correctly.

## System information

- BoTorch Version 0.9.1
- GPyTorch Version 1.11
- PyTorch Version 1.13.1+cpu

**Comment by esantorella** [comment]
Confirming that the code above still produces the same error as of today.

**Comment by adrian-martens** [comment]
Confirming that the code above still produces the error and was also encounterred in a different set up.

The issue seems to be the shape of `stdv` which is calculated from the target fidelity variance `variance_M`. Printing out the shapes before the line that raises the error gives:

`Max value samples (mvs): torch.Size([16, 10])`
`Actual fidelity mean (mean_m): torch.Size([16, 1])`
`Target fidelity stdv (stdv): torch.Size([1, 16])`

So `stdv` just needs to be transposed?

**Comment by Balandat** [comment]
> The issue seems to be the shape of stdv which is calculated from the target fidelity variance variance_M

Interesting observation. I did dig into this a bit more; it's not just that `stdv` needs to be transposed, doing that will still cause issues further down when `ratios` are computed. 

There is some nontrivial bug here in terms of how the shapes of `variance_M` and `covar_mM` are being handled with `qMultiFidelityLowerBoundMaxValueEntropy` when there are fantasies (this may be a more general bug, but if tensors are single-element if there are no fantasies then this may not actually cause any issues).

I don't have a ton of bandwidth to dig into this deeply right now - but I'd appreciate if anyone else has additional input to help resolve this.

**Comment by hvarfner** [comment]
Follow-up on this: The non-Lower bound variant (`qMultiFidelityMaxValueEntropy`) does not support q-batching at all. The forward pass has the decorator `@t_batch_mode_transform(expected_q=1)`, which throws an error during acquisition optimization. 

In this case, the repro is a bit off, since

```
MF_qMES = qMultiFidelityMaxValueEntropy(model, candidate_set)
acqvals = MF_qMES(train_X[:1])
```

will forward pass a tensor of shape `1 x d`, which doesn't trigger the error since it doesn't adhere to the acquisition function forward pass convention of `batch_shape x q x d`.

The `qLowerBound` variants should be fixed soon.

**Comment by Balandat** [comment]
@hvarfner This is done with #2930, right?

**Comment by hvarfner** [comment]
Yes!
