### ISSUE TITLE
[Bug] NaNs encountered in running fit_gpytorch_model  

### ISSUE THREAD

**Issue by satyanshukla** [pytorch/botorch#198]
# 🐛 Bug

I'm consistently encountering NaNs in the optimization loop of fit_gpytorch_model on simple examples. Any help would be appreciated.

## To reproduce

The code (relevant part) looks like this.
```python
def initialize_model(x0, y0, n=5):
    torch.manual_seed(0)
    # generate training data
    train_x = torch.randn(n, args.dim, device=device, dtype=dtype)
    
    train_obj = obj_func(decode(train_x), x0, y0)
    best_observed_value = train_obj.max().item()

    # define models for objective and constraint
    model = SingleTaskGP(train_X=train_x, train_Y=train_obj)
    model = model.to(train_x)

    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    mll = mll.to(train_x)

    return train_x, train_obj, mll, model, best_observed_value


def optimize_acqf_and_get_observation(acq_func, x0, y0):
    """Optimizes the acquisition function, and returns a new candidate and a noisy observation"""
    """
    with torch.no_grad():
        _, mu, logvar = vae_model(x0)
    bounds = torch.stack([mu - 3.0 * torch.exp(0.5 * logvar),
                          mu + 3.0 * torch.exp(0.5 * logvar)])
    """
    # optimize
    candidates = joint_optimize(
        acq_function=acq_func,
        bounds=bounds,
        q=BATCH_SIZE,
        num_restarts=10,
        raw_samples=200,
    )

    # observe new values
    new_x = candidates.detach()

    new_obj = obj_func(decode(new_x), x0, y0)
    return new_x, new_obj

def bayes_opt(x0, y0):
    #print(f"\nRunning BO ", end='')
    best_observed = []
    success = 0

    # call helper function to initialize model
    train_x, train_obj, mll, model, best_value = initialize_model(x0, y0, n=5)
    best_observed.append(best_value)
    #print(train_obj)
    # run N_BATCH rounds of BayesOpt after the initial random batch
    for itr in range(N_BATCH):

        fit_gpytorch_model(mll)

        # define the qNEI acquisition module using a QMC sampler
        qmc_sampler = SobolQMCNormalSampler(num_samples=MC_SAMPLES, seed=seed)
        qEI = qExpectedImprovement(model=model, sampler=qmc_sampler, best_f=best_value)

        # optimize and get new observation
        new_x, new_obj = optimize_acqf_and_get_observation(qEI, x0, y0)

        # update training points
        train_x = torch.cat((train_x, new_x))
        train_obj = torch.cat((train_obj, new_obj))

        # update progress
        #best_value = score_image_recognition(decode(train_x)).max().item()
        best_value, best_index = train_obj.max(0)
        best_observed.append(best_value.item())
        # reinitialize the model so it is ready for fitting on next iteration
        model.set_train_data(train_x, train_obj, strict=False)
        best_candidate = decode(train_x[best_index].unsqueeze(0))
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "vae_mnist2.py", line 371, in <module>
    attack_mnist_bayes(num_attacks=args.num_attacks)
  File "vae_mnist2.py", line 316, in attack_mnist_bayes
    itr, success, pert = bayes_opt(image, label)
  File "vae_mnist2.py", line 224, in bayes_opt
    fit_gpytorch_model(mll)
  File "/home/snshukla/py33/lib/python3.7/site-packages/botorch/fit.py", line 98, in fit_gpytorch_model
    mll, _ = optimizer(mll, track_iterations=False, **kwargs)
  File "/home/snshukla/py33/lib/python3.7/site-packages/botorch/optim/fit.py", line 192, in fit_gpytorch_scipy
    callback=cb,
  File "/home/snshukla/py33/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 600, in minimize
    callback=callback, **options)
  File "/home/snshukla/py33/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/snshukla/py33/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/home/snshukla/py33/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/snshukla/py33/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 64, in __call__
    fg = self.fun(x, *args)
  File "/home/snshukla/py33/lib/python3.7/site-packages/botorch/optim/fit.py", line 239, in _scipy_objective_and_grad
    raise e  # pragma: nocover
  File "/home/snshukla/py33/lib/python3.7/site-packages/botorch/optim/fit.py", line 234, in _scipy_objective_and_grad
    loss = -mll(*args).sum()
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/module.py", line 22, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 28, in forward
    res = output.log_prob(target)
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/distributions/multivariate_normal.py", line 128, in log_prob
    inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1041, in inv_quad_logdet
    *args,
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/functions/_inv_quad_log_det.py", line 112, in forward
    solves, t_mat = lazy_tsr._solve(rhs, preconditioner, num_tridiag=num_random_probes)
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 630, in _solve
    preconditioner=preconditioner,
  File "/home/snshukla/py33/lib/python3.7/site-packages/gpytorch/utils/linear_cg.py", line 161, in linear_cg
    raise RuntimeError("NaNs encounterd when trying to perform matrix-vector multiplication")
RuntimeError: NaNs encounterd when trying to perform matrix-vector multiplication
```

## System information

**Please complete the following information:**
-  BoTorch Version: 0.1.1
-  GPyTorch Version: 0.3.3
-  PyTorch Version: 1.1.0 
-  Computer OS: CentOS

**Comment by Balandat** [comment]
Are you running this on the GPU? If so, this is likely related to the PyTorch bug in #197 (for which gpytorch is about to release a workaround soon).

**Comment by satyanshukla** [comment]
Yes, I'm running on GPU. Are you saying this error won't come if I run on CPU?

**Comment by Balandat** [comment]
> Are you saying this error won't come if I run on CPU?

Yes, at least that's what I strongly suspect. There is a bug in core pytorch that results in incorrect derivatives on the GPU (see above). This totally throws off the optimizer and fitting fails. We're going to do a minor version bump as soon as GPyTorch releases a version with their hotfix. If you run on GPyTorch master you should not see this issue.

**Comment by Balandat** [comment]
@satyanshukla does running on the CPU / using the most recent gpytorch master resolve this issue?

**Comment by satyanshukla** [comment]
No, running on CPU does not solve this issue. I am already using the most recent gpytorch master.

**Comment by Balandat** [comment]
This is likely related to not normalizing/standardizing the domain and observations. The priors int the default models in BoTorch work best if the domain is the unit cube `[0, 1]^d` and the observations are standardized (zero mean, unit variance). If your inputs are far away from that you may run into the issues you observe (and likely get a worse fit).

**Comment by Balandat** [comment]
@satyanshukla Are you still running into this issue?

**Comment by satyanshukla** [comment]
Normalizing observations solved this problem in cases where observations were far from standard normal. But in some situations running the fit function again worked.

**Comment by Balandat** [comment]
Great. I'll close this out then.
