### ISSUE TITLE
[Bug] fail to reproduce the tutorial

### ISSUE THREAD

**Issue by StanleyYoo** [pytorch/botorch#2062]
# 🐛 Bug

Hi and thanks for your support in advance.

related to the tutorial [https://botorch.org/tutorials/custom_botorch_model_in_ax] it keep complaining following errors:

```
Running Sobol initialization trials...
Running GP+EI optimization trial 6/35...
Traceback (most recent call last):
  File "C:\Users\xxx.py", line 278, in <module>        
    gpei = get_model_bridge(experiment=exp, data=exp.fetch_data())
  File "C:\Users\xxx.py", line 206, in get_model_bridge
    model = Models.BOTORCH_MODULAR(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\modelbridge\registry.py", line 344, in __call__
    model_bridge = bridge_class(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\modelbridge\torch.py", line 124, in __init__
    super().__init__(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\modelbridge\base.py", line 179, in __init__ 
    self._fit(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\modelbridge\torch.py", line 511, in _fit
    self.model.fit(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\models\torch\botorch_modular\model.py", line 277, in fit
    self._surrogates[Keys.ONLY_SURROGATE].fit(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py", line 543, in fit
    self.construct(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py", line 244, in construct
    self._construct_model_list(
  File "C:\Users\XXXX\.venv\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py", line 431, in _construct_model_list
    submodels.append(model_cls(**formatted_model_inputs))
TypeError: SimpleCustomGP.__init__() got an unexpected keyword argument 'train_Yvar'
```

My code is below:
```
class SimpleCustomGP(ExactGP, GPyTorchModel):
    _num_outputs = 1  # to inform GPyTorchModel API

    def __init__(self, train_X, train_Y):
        # squeeze output dim before passing train_Y to ExactGP
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood())
        self.mean_module = ConstantMean()
        self.covar_module = ScaleKernel(
            base_kernel=RBFKernel(ard_num_dims=train_X.shape[-1]),
        )
        self.to(train_X)  # make sure we're on the right device/dtype

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return MultivariateNormal(mean_x, covar_x)


def get_model_bridge(experiment: Experiment,
                     data: Data):
    model = Models.BOTORCH_MODULAR(
        # Required
        experiment = experiment,
        data = data,

        # Optional
        botorch_acqf_class=qExpectedImprovement,
        #botorch_acqf_class=qKnowledgeGradient
        surrogate=Surrogate(
            botorch_model_class=SimpleCustomGP,
        )
    )
    return model

print(f"Running Sobol initialization trials...")
sobol = Models.SOBOL(search_space=exp.search_space)

for i in range(NUM_SOBOL_TRIALS):
    # Produce a GeneratorRun from the model, which contains proposed arm(s) and other metadata
    generator_run = sobol.gen(n=1)
    # Add generator run to a trial to make it part of the experiment and evaluate arm(s) in it
    trial = exp.new_trial(generator_run=generator_run)
    # Start trial run to evaluate arm(s) in the trial
    trial.run()
    # Mark trial as completed to record when a trial run is completed
    # and enable fetching of data for metrics on the experiment
    # (by default, trials must be completed before metrics can fetch their data,
    # unless a metric is explicitly configured otherwise)
    trial.mark_completed()

for i in range(NUM_BOTORCH_TRIALS):
    print(
        f"Running GP+EI optimization trial {i + NUM_SOBOL_TRIALS + 1}/{NUM_SOBOL_TRIALS + NUM_BOTORCH_TRIALS}..."
    )
    # Reinitialize GP+EI model at each step with updated data.
    gpei = get_model_bridge(experiment=exp, data=exp.fetch_data())
    # gpei = Models.BOTORCH(experiment=exp, data=exp.fetch_data())
    generator_run = gpei.gen(n=1)
    trial = exp.new_trial(generator_run=generator_run)
    trial.run()
    trial.mark_completed()
    save_experiment(exp, filepath, encoder_registry=bundle.encoder_registry)
```

Could you please advise how to resolve this?

BR, Stanley

**Comment by saitcakmak** [comment]
Yeah, looks like `SimpleCustomGP` needs to accept `train_Yvar`.

**Comment by saitcakmak** [comment]
I am guessing the tutorial did not fail in the CI since the original evaluation / objective function the tutorial uses does not produce noise observations. @StanleyYoo I am assuming you changed the evaluation function here, is that correct?

**Comment by saitcakmak** [comment]
This should be resolved in the updated tutorial. Feel free to re-open if you run into further issues.
