### ISSUE TITLE
[Bug] Error occurred when I deployed Botorch version 0.6.0

### ISSUE THREAD

**Issue by lpj20** [pytorch/botorch#2149]
Hello,

I deployed botorch 0.6.0 on my Ubuntu server because I need the TrainingData module in the old version. But when I executed "pip install -e ." there was an error related to scm that I cannot solve.

        Processing /root/software/botorch-0.6.0
        Installing build dependencies ... done
        Getting requirements to build wheel ... done
        Preparing metadata (pyproject.toml) ... error
        error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [48 lines of output]
        /tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py:30: RuntimeWarning:
        ERROR: setuptools==47.3.2 is used in combination with setuptools_scm>=8.x
      
      Your build configuration is incomplete and previously worked by accident!
      setuptools_scm requires setuptools>=61
      
      Suggested workaround if applicable:
       - migrating from the deprecated setup_requires mechanism to pep517/518
         and using a pyproject.toml to declare build dependencies
         which are reliably pre-installed before running the build tools
      
        warnings.warn(
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 50, in <module>
          setup(
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 161, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.9/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 425, in __init__
          _Distribution.__init__(self, {
        File "/opt/conda/lib/python3.9/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 717, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 101, in version_keyword
          _assign_version(dist, config)
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 56, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /root/software/botorch-0.6.0.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      × Encountered error while generating package metadata.
      ╰─> See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.`

I was wondering if you could help me on this. Many thx!

**Comment by Balandat** [comment]
/tmp/pip-build-env-wun2yu7a/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py:30: RuntimeWarning:
    ERROR: setuptools==47.3.2 is used in combination with setuptools_scm>=8.x

Seems like this is the issue? You may have some other package in your environment that pins setuptools to an old version that is incompatible with setuptools_scm. Have you tried installing this into a clean environment? How are you installing botorch here?

**Comment by lpj20** [comment]
Hi, @Balandat , thanks for your rapid response. Actually, I created a new conda environment and tried different kinds of versions of setuptools (both 47.3.2 and 69.0.2), because there is an instruction " setuptools_scm requires setuptools>=61". However, I saw there is a conflict setuptools requirment in pyproject.toml file(setuptools<48), so I am wondering which version of setuptools I need to install.
Below is the error message when I installed the setuptools with the 69.0.2 version:
`

        Obtaining file:///root/software/botorch-0.6.0
        Installing build dependencies ... done
        Checking if build backend supports build_editable ... done
        Getting requirements to build wheel ... done
        Preparing metadata (pyproject.toml) ... error
        error: subprocess-exited-with-error
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [48 lines of output]
        /tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py:30:    
                             
        RuntimeWarning:
        ERROR: setuptools==47.3.2 is used in combination with setuptools_scm>=8.x
        Your build configuration is incomplete and previously worked by accident!
        setuptools_scm requires setuptools>=61
      
      Suggested workaround if applicable:
       - migrating from the deprecated setup_requires mechanism to pep517/518
         and using a pyproject.toml to declare build dependencies
         which are reliably pre-installed before running the build tools
      
        warnings.warn(
      Traceback (most recent call last):
        File "/opt/conda/envs/baichen/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/envs/baichen/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/envs/baichen/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 50, in <module>
          setup(
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 161, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/envs/baichen/lib/python3.9/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 425, in __init__
          _Distribution.__init__(self, {
        File "/opt/conda/envs/baichen/lib/python3.9/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 717, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 101, in version_keyword
          _assign_version(dist, config)
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 56, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-14pjps47/overlay/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /root/software/botorch-0.6.0.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
        note: This error originates from a subprocess, and is likely not a problem with pip.
        error: metadata-generation-failed

        × Encountered error while generating package metadata.
        ╰─> See above for output.

        note: This is an issue with the package mentioned above, not pip.
        hint: See above for details.`
The installation flow is to download the 0.6.0 version of Botorch and unzip the files, then I entered the botorch dir and executed "pip install -e ."

**Comment by Balandat** [comment]
Hmm I see we actually pinned the `setuptools` version back in the 0.6.0 release. There is nothing we can do retroactively here - one thing you could try to do is to manually apply the changes from #1292 and #1318 locally and then install botorch from the edited copy of the repo. |

Is there a particular reason you need the old `TrainingData` API (rather than the newer `Dataset` one)? 0.6.0 is very old and there have been a lot of improvements since so I highly recommend using a more recent version.

**Comment by lpj20** [comment]
@Balandat thx. Since I am now executing a code with `TrainingData` API written a few years ago. Fortunately, I have solved this problem by using the command "pip install botorch==0.6.0" directly. Thx again for your help!
