### ISSUE TITLE
fit_gpytorch_mll problems

### ISSUE THREAD

**Issue by ToennisStef** [pytorch/botorch#2182]
## Issue description

I am a beginner in botorch and i have troubles understanding the problem im facing when using the "fit_gpytorch_mll" function. I try to implement an easy 1d-input 1d-output baysian optimization loop of the forester function (taken from the "virtual library of simulation experiments"). 

When i try to optimize the "fit_gpytorch_mll" function often throws the error message "ModelFittingError: All attempts to fit the model have failed." 

While browsing for possible reasons i came across one explainiation that described problems occuring when there are close or repeated obersations in the training data. Close or repeated observations could lead to an ill-conditioned covaraince matix of the GP and thous to a non invertable matrix therefore the whole hyperparameter optimization would terminate and return an error. 

At first i thought this was the problem. But after looking more closely at my data an playing around a bit with different random seeds i could rule that reason out. 

I tried optimization of the hyperparameters with the "torch.optim.Adam" optimizer. When using this optimizer with a custom optimization loop no errors occured.

I tried to standardize the Y values. This helped a little. But in the end i randomly saw that someone used `torch.set_default_dtype(torch.double)` to avoid numerical issues. And this basically has done the trick for me here but i still don't really get why. I have trouble understanding why this helped in the end.

Another question would be if 

## Code example

The following code is for error reproduction:
```

import math
import numpy as np
import gpytorch
import torch
import botorch
from torch import Tensor
from typing import Optional
from botorch.fit import fit_gpytorch_mll

def torchForresterFunction(X):
    """
    Implementation of Forrester optimization test function returning a torch tensor
    """
    Y = torch.pow(6*X-2,2)*torch.sin(12*X-4)
    return Y
class ExactGP(gpytorch.models.ExactGP, botorch.models.gpytorch.GPyTorchModel):

    _num_outputs = 1  # to inform GPyTorchModel API

    def __init__(self, train_X, train_Y, Likelihood):
        super().__init__(train_X, train_Y, Likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel()) 

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
#Inference points for plotting:
X = torch.linspace(0,1,100)
Y = (-1)*torchForresterFunction(X)

#Set random seed for reproducability
torch.manual_seed(11111)

#set sample size and adjust sample variance
n_samples = 15
sample_var = 0.5

#set training data
X_train = torch.rand(n_samples)
Y_train = (-1)*torchForresterFunction(X_train) + torch.randn(n_samples)*sample_var

from botorch.acquisition import ExpectedImprovement

def candidate_in_range(candidate, X_train, tol):
    for x in X_train:
            if (x-tol <= candidate <= x+tol):
                return True
    return False  

from botorch.optim import optimize_acqf
import os
smoke_test = ('CI' in os.environ)
trainitraining_iter_hyperparameters = 2 if smoke_test else 500

bounds = torch.stack([torch.zeros(1), torch.ones(1)])
tol2 = 1e-4

with botorch.settings.debug(True):
    for i in range(50):
        
        #Re-Initialize for each BO-step
        likelihood = gpytorch.likelihoods.GaussianLikelihood()
        model = ExactGP(X_train, Y_train, likelihood)
        
        #set the model and the likelihood into training mode
        model.train
        likelihood.train
        #Fit the model to the data
        mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
        fit_gpytorch_mll(mll, )
        
        #Define the expected improvement acquisition function with the re-initialized model
        EI = ExpectedImprovement(model, max(Y_train))

        #optimize the acquisition function
        candidate_EI, acq_value_EI = optimize_acqf(
            EI, bounds=bounds, q=1, num_restarts=5, raw_samples=20,
        )

        #Append the the optimal candidate and get noisy function evaluation for canditate. Then append data
        X_op = candidate_EI
        #Check if we have repeated or close observations
        if candidate_in_range(candidate_EI,X_train,tol2) == True:
            break
        Y_op = (-1)*torchForresterFunction(X_op[0]) + torch.randn(1)*sample_var
        X_train = torch.cat((X_train,X_op[0]))
        Y_train = torch.cat((Y_train,Y_op))
        print("Iteration: ", i, "Canditate X-Value:" , X_train[-1])


```

This is the cell output with the error:
```

Iteration:  0 Canditate X-Value: tensor(0.7613)
Iteration:  1 Canditate X-Value: tensor(0.7618)
Iteration:  2 Canditate X-Value: tensor(0.2767)
Iteration:  3 Canditate X-Value: tensor(0.7579)
Iteration:  4 Canditate X-Value: tensor(0.7586)
Iteration:  5 Canditate X-Value: tensor(0.4355)
Iteration:  6 Canditate X-Value: tensor(0.7209)
Iteration:  7 Canditate X-Value: tensor(0.7632)
c:\ProgramData\Anaconda3\envs\BO_init\Lib\site-packages\botorch\optim\fit.py:102: OptimizationWarning: `scipy_minimize` terminated with status OptimizationStatus.FAILURE, displaying original message from `scipy.optimize.minimize`: ABNORMAL_TERMINATION_IN_LNSRCH
  warn(
c:\ProgramData\Anaconda3\envs\BO_init\Lib\site-packages\botorch\optim\fit.py:102: OptimizationWarning: `scipy_minimize` terminated with status OptimizationStatus.FAILURE, displaying original message from `scipy.optimize.minimize`: ABNORMAL_TERMINATION_IN_LNSRCH
  warn(
c:\ProgramData\Anaconda3\envs\BO_init\Lib\site-packages\botorch\optim\fit.py:102: OptimizationWarning: `scipy_minimize` terminated with status OptimizationStatus.FAILURE, displaying original message from `scipy.optimize.minimize`: ABNORMAL_TERMINATION_IN_LNSRCH
  warn(
c:\ProgramData\Anaconda3\envs\BO_init\Lib\site-packages\botorch\optim\fit.py:102: OptimizationWarning: `scipy_minimize` terminated with status OptimizationStatus.FAILURE, displaying original message from `scipy.optimize.minimize`: ABNORMAL_TERMINATION_IN_LNSRCH
  warn(
c:\ProgramData\Anaconda3\envs\BO_init\Lib\site-packages\botorch\optim\fit.py:102: OptimizationWarning: `scipy_minimize` terminated with status OptimizationStatus.FAILURE, displaying original message from `scipy.optimize.minimize`: ABNORMAL_TERMINATION_IN_LNSRCH
  warn(


```
```

{
	"name": "ModelFittingError",
	"message": "All attempts to fit the model have failed.",
	"stack": "---------------------------------------------------------------------------
ModelFittingError                         Traceback (most recent call last)
Cell In[11], line 27
     25 #Fit the model to the data
     26 mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
---> 27 fit_gpytorch_mll(mll, )
     29 #Define the expected improvement acquisition function with the re-initialized model
     30 EI = ExpectedImprovement(model, max(Y_train))

File c:\\ProgramData\\Anaconda3\\envs\\BO_init\\Lib\\site-packages\\botorch\\fit.py:105, in fit_gpytorch_mll(mll, closure, optimizer, closure_kwargs, optimizer_kwargs, **kwargs)
    102 if optimizer is not None:  # defer to per-method defaults
    103     kwargs[\"optimizer\"] = optimizer
--> 105 return FitGPyTorchMLL(
    106     mll,
    107     type(mll.likelihood),
    108     type(mll.model),
    109     closure=closure,
    110     closure_kwargs=closure_kwargs,
    111     optimizer_kwargs=optimizer_kwargs,
    112     **kwargs,
    113 )

File c:\\ProgramData\\Anaconda3\\envs\\BO_init\\Lib\\site-packages\\botorch\\utils\\dispatcher.py:93, in Dispatcher.__call__(self, *args, **kwargs)
     91 func = self.__getitem__(types=types)
     92 try:
---> 93     return func(*args, **kwargs)
     94 except MDNotImplementedError:
     95     # Traverses registered methods in order, yields whenever a match is found
     96     funcs = self.dispatch_iter(*types)

File c:\\ProgramData\\Anaconda3\\envs\\BO_init\\Lib\\site-packages\\botorch\\fit.py:283, in _fit_fallback(mll, _, __, closure, optimizer, closure_kwargs, optimizer_kwargs, max_attempts, warning_handler, caught_exception_types, **ignore)
    280 if debug.off():
    281     msg = msg + \" For more information, try enabling botorch.settings.debug mode.\"
--> 283 raise ModelFittingError(msg)

ModelFittingError: All attempts to fit the model have failed."
}
```

I hope this is readable an I hope someone can help me with regards to understanding why just setting the default dtype in torch solved the problem.

## System Info

- BoTorch Version 0.9.4
- GPyTorch Version 1.11
- PyTorch Version 2.1.1+cu118
- Computer OS: Windows

**Comment by sdaulton** [comment]
Hi @ToennisStef!

I'd recommend:
- standarizing the training Y_train by subtracting the mean and dividing by the standard deviation: https://github.com/pytorch/botorch/blob/4efdf2646e5ef6229f3492c3556fb8fe170881a6/botorch/utils/transforms.py#L26. 
- using the SingleTaskGP in botorch: https://github.com/search?q=repo%3Apytorch%2Fbotorch%20class%20singletaskgp&type=code. The default priors typically improve numerical stability.
- For better BO performance, you probably want to use qLogNoisyExpectedImprovement since your observations are noisy: https://github.com/search?q=repo%3Apytorch%2Fbotorch%20class%20qlognoisyexpected&type=code

Depending on your use case, you may find it easier to work with Ax, which takes care of these subtle but important details: https://github.com/facebook/Ax/blob/main/tutorials/gpei_hartmann_service.ipynb

**Comment by Balandat** [comment]
@ToennisStef were you able to resolve your issue with the above pointers?

**Comment by esantorella** [comment]
Closing as inactive, but feel free to reopen with further questions.

**Comment by lixiangru123** [comment]
I met the same problem, and I could fit it normally at the beginning, but after searching for a period of time, the same error appeared, may I ask if there is a good solution，I've tried the double type and normalization
`Traceback (most recent call last):
  File "/home/eda240601/SCBO_main.py", line 307, in <module>
    model = get_fitted_model(train_X, Area)
  File "/home/eda240601/SCBO_main.py", line 243, in get_fitted_model
    fit_gpytorch_mll(mll)
  File "/home/eda240601/.local/lib/python3.9/site-packages/botorch/fit.py", line 105, in fit_gpytorch_mll
    return FitGPyTorchMLL(
  File "/home/eda240601/.local/lib/python3.9/site-packages/botorch/utils/dispatcher.py", line 93, in __call__
    return func(*args, **kwargs)
  File "/home/eda240601/.local/lib/python3.9/site-packages/botorch/fit.py", line 283, in _fit_fallback
    raise ModelFittingError(msg)
botorch.exceptions.errors.ModelFittingError: All attempts to fit the model have failed. For more information, try enabling botorch.settings.debug mode.
`



`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.double
tkwargs = {"device": device, "dtype": dtype}
Area = torch.tensor(A_list, **tkwargs).unsqueeze(-1)
L40 = torch.tensor(L40, **tkwargs).unsqueeze(-1)
Q40 = torch.tensor(Q40, **tkwargs).unsqueeze(-1)
fSRF = torch.tensor(fSRF, **tkwargs).unsqueeze(-1)
################################################
C1=torch.tensor(Area-10000, **tkwargs)
C2=torch.tensor((abs(L40-Lt)/Lt)-0.05, **tkwargs)
C3 = torch.tensor(Qt-Q40, **tkwargs)
C4 = torch.tensor(80-fSRF, **tkwargs)`
