### ISSUE TITLE
[Bug] Inefficient posterior evaluation of `SaasFullyBayesianSingleTaskGP` when `q=1`

### ISSUE THREAD

**Issue by slishak-PX** [pytorch/botorch#2310]
# 🐛 Bug

Evaluating an acquisition function with `q=1` with `SaasFullyBayesianSingleTaskGP` requires an unnecessarily large amount of memory, due to an inefficient broadcasted `matmul` operation.

In the example below, the following line multiplies a tensor of size `[256, 16, 1, 2048]` with a tensor of size `[16, 2048, 2048]` which requires the allocation of 128GB of memory:
https://github.com/cornellius-gp/gpytorch/blob/9551eba889adf835b69cfd86e9a5d584fb61cdcc/gpytorch/models/exact_prediction_strategies.py#L118

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.models.fully_bayesian import SaasFullyBayesianSingleTaskGP
from botorch.models.transforms import Standardize
from botorch import fit_fully_bayesian_model_nuts
from botorch.acquisition import UpperConfidenceBound

n_train = 2048
n_test = 256
d = 256

tkwargs = {
    "device": torch.device("cuda:3" if torch.cuda.is_available() else "cpu"),
    "dtype": torch.double,
}

train_X = torch.rand(n_train, d, **tkwargs)
test_X = torch.rand(n_test, d, **tkwargs)
train_Y = torch.sin(train_X[:, :1])
test_Y = torch.sin(test_X[:, :1])

gp = SaasFullyBayesianSingleTaskGP(
    train_X=train_X, 
    train_Y=train_Y, 
    outcome_transform=Standardize(m=1),
)
fit_fully_bayesian_model_nuts(
    gp,
    warmup_steps=4,
    num_samples=16,
    thinning=1,
)

ucb = UpperConfidenceBound(gp, beta=2.5)
acq_values = ucb(test_X[:, None, :])
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/tmp/ipykernel_3377365/3398296989.py", line 3, in <module>
    acq_values = ucb(test_X[:, None, :])
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/botorch/utils/transforms.py", line 259, in decorated
    output = method(acqf, X, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/botorch/acquisition/analytic.py", line 786, in forward
    mean, sigma = self._mean_and_sigma(X)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/botorch/acquisition/analytic.py", line 106, in _mean_and_sigma
    posterior = self.model.posterior(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/botorch/models/fully_bayesian.py", line 536, in posterior
    posterior = super().posterior(
                ^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.11/site-packages/botorch/models/gpytorch.py", line 383, in posterior
    mvn = self(X)
          ^^^^^^^
...
    return test_train_covar.matmul(precomputed_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 GiB. GPU 3 has a total capacity of 79.15 GiB of which 44.45 GiB is free. Including non-PyTorch memory, this process has 34.69 GiB memory in use. Of the allocated memory 23.74 GiB is allocated by PyTorch, and 10.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```

## Expected Behavior

The memory usage for this operation is very high because `torch.matmul` is inefficient for such batched matrix-vector multiplications. If the same operation is written as an `einsum`, or transposing such that it's a matrix-matrix multiplication, the memory usage and computation time are substantially reduced.

For example, below is a demonstration of two alternative operations which reduce the memory and computation time by orders of magnitude:
```python
import torch
device = "cuda:3"

# Matrices to multiply
torch.manual_seed(50)
a = torch.randn((256, 16, 1, 1024), device=device)
b = torch.randn((16, 1024, 1024), device=device)

def profile(func, n_repeat=1000):
    torch.cuda.reset_peak_memory_stats(device=device)
    m0 = torch.cuda.max_memory_allocated(device=device)

    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)

    start.record()
    out = func()
    end.record()

    torch.cuda.synchronize()
    t = start.elapsed_time(end)

    m1 = torch.cuda.max_memory_allocated(device=device)

    print(f"Memory used: {(m1 - m0) / 1024**3:.2f}GB")
    print(f"Time: {1e6 * t / n_repeat:.6f} us")

    return out

with torch.no_grad():
    print("matmul")
    c = profile(lambda: torch.matmul(a, b), n_repeat=100)

    print("\neinsum")
    c_einsum = profile(lambda: torch.einsum("...ij,...jk", a, b))
    print(f"Max error: {(c_einsum - c).abs().max().cpu().item():.7f}")

    print("\ntransposed matmul")
    c_transpose = profile(lambda: torch.matmul(a.transpose(0, 2), b).transpose(0, 2))
    print(f"Max error: {(c_transpose - c).abs().max().cpu().item():.7f}")
```

```
matmul
Memory used: 16.02GB
Time: 2294.719964 us

einsum
Memory used: 0.02GB
Time: 154.655993 us
Max error: 0.0002327

transposed matmul
Memory used: 0.02GB
Time: 102.880001 us
Max error: 0.0002327
```

## System information

**Please complete the following information:**
- BoTorch Version 1.11
- GPyTorch Version 0.9.5
- PyTorch Version 2.2.0+cu121
- Computer OS: Rocky Linux release 8.9
- GPU: NVIDIA A100 80GB PCIe

**Comment by Balandat** [comment]
Thanks for raising this, this is a great catch. Since this call happens in gpytorch we'll have to make a change there and ensure that it is compatible with all kinds of other (non-fully-Bayesian) scenarios (not sure what kinds of shape exactly are encountered in this call), but we will definitely fix this. 

cc @dme65, @esantorella

**Comment by slishak-PX** [comment]
Thank you! I did initially try and come up with something to contribute to GPyTorch and/or linear_operator, but it was harder than anticipated to make it compatible and not introduce slowdowns in other situations, so I thought I'd report it here for now. For example, `einsum` is faster than `matmul` in this specific situation but has the potential to be much slower in other situations.

(n.b. I've just corrected a small mistake in the profiling code in the issue above)

**Comment by Balandat** [comment]
> I did initially try and come up with something to contribute to GPyTorch and/or linear_operator, but it was harder than anticipated to make it compatible and not introduce slowdowns in other situations, so I thought I'd report it here for now. 

Interesting. Do you happen to have have some artifacts of those attempts that you could share? That would be very helpful.

**Comment by slishak-PX** [comment]
There is a very similar issue with `KroneckerMultiTaskGP`. Below is a minimum reproducible example.

```python
import torch
from botorch.models import KroneckerMultiTaskGP

n_inputs = 10
n_tasks = 4
n_train = 2048
n_test = 1
device = torch.device("cuda:3")

train_x = torch.randn(n_train, n_inputs, dtype=torch.float64, device=device)
train_y = torch.randn(n_train, n_tasks, dtype=torch.float64, device=device)

test_x = torch.randn(n_test, n_inputs, dtype=torch.float64, device=device)

gp = KroneckerMultiTaskGP(train_x, train_y)

posterior = gp.posterior(test_x)
posterior.rsample(torch.Size([256, 1]))
```

<details>
<summary>Stack trace</summary>

```
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[7], line 18
     15 gp = KroneckerMultiTaskGP(train_x, train_y)
     17 posterior = gp.posterior(test_x)
---> 18 posterior.rsample(torch.Size([256, 1]))

File ~/miniconda3/envs/al/lib/python3.10/site-packages/botorch/posteriors/multitask.py:269, in MultitaskGPPosterior.rsample(self, sample_shape)
    267 if sample_shape is None:
    268     sample_shape = torch.Size([1])
--> 269 return self.rsample_from_base_samples(
    270     sample_shape=sample_shape, base_samples=None
    271 )

File ~/miniconda3/envs/al/lib/python3.10/site-packages/botorch/posteriors/multitask.py:229, in MultitaskGPPosterior.rsample_from_base_samples(self, sample_shape, base_samples, train_diff)
    225 obs_minus_samples = (
    226     train_diff.reshape(*train_diff.shape[:-2], -1) - updated_obs_samples
    227 )
    228 train_covar_plus_noise = self.train_train_covar + self.train_noise
--> 229 obs_solve = train_covar_plus_noise.solve(obs_minus_samples.unsqueeze(-1))
    231 # and multiply the test-observed matrix against the result of the solve
    232 updated_samples = self.test_train_covar.matmul(obs_solve).squeeze(-1)

File ~/miniconda3/envs/al/lib/python3.10/site-packages/linear_operator/operators/_linear_operator.py:2334, in LinearOperator.solve(self, right_tensor, left_tensor)
   2332 func = Solve
   2333 if left_tensor is None:
-> 2334     return func.apply(self.representation_tree(), False, right_tensor, *self.representation())
   2335 else:
   2336     return func.apply(
   2337         self.representation_tree(),
   2338         True,
   (...)
   2341         *self.representation(),
   2342     )

File ~/miniconda3/envs/al/lib/python3.10/site-packages/torch/autograd/function.py:506, in Function.apply(cls, *args, **kwargs)
    503 if not torch._C._are_functorch_transforms_active():
    504     # See NOTE: [functorch vjp and autograd interaction]
    505     args = _functorch.utils.unwrap_dead_wrappers(args)
--> 506     return super().apply(*args, **kwargs)  # type: ignore[misc]
    508 if cls.setup_context == _SingleLevelFunction.setup_context:
    509     raise RuntimeError(
    510         'In order to use an autograd.Function with functorch transforms '
    511         '(vmap, grad, jvp, jacrev, ...), it must override the setup_context '
    512         'staticmethod. For more details, please see '
    513         'https://pytorch.org/docs/master/notes/extending.func.html')

File ~/miniconda3/envs/al/lib/python3.10/site-packages/linear_operator/functions/_solve.py:53, in Solve.forward(ctx, representation_tree, has_left, *args)
     51     res = left_tensor @ res
     52 else:
---> 53     solves = _solve(linear_op, right_tensor)
     54     res = solves
     56 if ctx.is_vector:

File ~/miniconda3/envs/al/lib/python3.10/site-packages/linear_operator/functions/_solve.py:17, in _solve(linear_op, rhs)
     15     return linear_op.solve(rhs)
     16 if settings.fast_computations.solves.off() or linear_op.size(-1) <= settings.max_cholesky_size.value():
---> 17     return linear_op.cholesky()._cholesky_solve(rhs)
     18 else:
     19     with torch.no_grad():

File ~/miniconda3/envs/al/lib/python3.10/site-packages/linear_operator/operators/triangular_linear_operator.py:78, in TriangularLinearOperator._cholesky_solve(self, rhs, upper)
     71 def _cholesky_solve(
     72     self: Float[LinearOperator, "*batch N N"],
     73     rhs: Union[Float[LinearOperator, "*batch2 N M"], Float[Tensor, "*batch2 N M"]],
     74     upper: Optional[bool] = False,
     75 ) -> Union[Float[LinearOperator, "... N M"], Float[Tensor, "... N M"]]:
     76     # use custom method if implemented
     77     try:
---> 78         res = self._tensor._cholesky_solve(rhs=rhs, upper=upper)
     79     except NotImplementedError:
     80         if upper:
     81             # res = (U.T @ U)^-1 @ v = U^-1 @ U^-T @ v

File ~/miniconda3/envs/al/lib/python3.10/site-packages/linear_operator/operators/dense_linear_operator.py:38, in DenseLinearOperator._cholesky_solve(self, rhs, upper)
     33 def _cholesky_solve(
     34     self: Float[LinearOperator, "*batch N N"],
     35     rhs: Union[Float[LinearOperator, "*batch2 N M"], Float[Tensor, "*batch2 N M"]],
     36     upper: Optional[bool] = False,
     37 ) -> Union[Float[LinearOperator, "... N M"], Float[Tensor, "... N M"]]:
---> 38     return torch.cholesky_solve(rhs, self.to_dense(), upper=upper)

OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 GiB (GPU 3; 79.19 GiB total capacity; 4.73 GiB already allocated; 71.26 GiB free; 5.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
</details>

The final line requires allocation of 128GB of GPU memory, because of the call to `torch.cholesky_solve` with B shaped `(256, 1, 8192, 1)` and L shaped `(8192, 8192)`.

The following line appears to be the root cause. Unsqueezing the last dimension sets up a batched matrix-vector solve, but if we instead transpose one of the batch dimensions to the end, we do a more efficient matrix-matrix solve.
https://github.com/pytorch/botorch/blob/4497a5c5df7183a1f90219c818e58d172b368cf8/botorch/posteriors/multitask.py#L229

For example, the following code requires less than 4GB of GPU memory, and I believe it is equivalent. By moving the first batch dimension to the final position, we at least stand the chance of having a more efficient operation if the first batch dimension is greater than 1. It would probably be even better to find the largest batch dimension and move that one to the end.

```python
perm = list(range(1, obs_minus_samples.ndim)) + [0]
inverse_perm = torch.argsort(torch.tensor(perm))

obs_minus_samples_p = obs_minus_samples.permute(*perm)
obs_solve = train_covar_plus_noise.solve(obs_minus_samples_p)

# and multiply the test-observed matrix against the result of the solve
updated_samples = self.test_train_covar.matmul(obs_solve).permute(*inverse_perm)
```

@Balandat @esantorella: should I submit a PR for this, or is there an obvious reason that it wouldn't work in other use cases?

**Comment by Balandat** [comment]
> should I submit a PR for this, or is there an obvious reason that it wouldn't work in other use cases?

A PR for this would be great - I don't see any obvious reason why this wouldn't work in other cases. Ideally, we could even do this at the level of `LinearOperator.solve()` so that other cases can also benefit from this. Even more ideal, this could be done at the level of pytorch's `torch.cholesky_solve()` under the hood, but that would be a larger lift - though it's probably worth raising this with the pytorch folks to understand whether there are any plans in that direction. cc @gpleiss, @jacobrgardner

> It would probably be even better to find the largest batch dimension and move that one to the end, or even flatten them all.

Yes, that makes sense. There are probably some nontrivial tradeoffs between flattening them all and keeping them around depending on how exactly the underlying cuda kernel parallelizes the evaluation in each case.

**Comment by Balandat** [comment]
cc @sdaulton, @jandylin, @SebastianAment  re excessive memory usage in Kronecker MTGPs

**Comment by Balandat** [comment]
cc @JonathanWenger

**Comment by ayesharoxx** [comment]
Hi, I had a similar issue and got some useful insights from this post. However, now I am encountering a memory error in matern_kernel.py at this line- : 
x2_ = (x2 - mean).div(self.lengthscale)

Here are my x1, mean and x2 shapes at this point.
x1.shape = torch.Size([32, 50, 16, 1, 100])
mean.shape = torch.Size([32, 50, 16, 1, 100])
x2.shape = torch.Size([32, 50, 16, 1611, 100])
I am using qknowledgeGradient in optimise_acqf with raw_samples = 50, q=1, num_samples(because I am using SaasFullyBayesianSingleTaskGP) = 256, thinning = 16.

The error I get is -  line 101, in forward
    x2_ = (x2 - mean).div(self.lengthscale)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 32993280000 bytes.

Is there any way to fix this? Thanks !
