### ISSUE TITLE
[Bug] _get_noiseless_fantasy_model for LogNoisyExpectedImprovement and NoisyExpectedImprovement only works for default GP with default Matern & no input or outcome transforms

### ISSUE THREAD

**Issue by 71c** [pytorch/botorch#2412]
# 🐛 Bug

In `botorch/acquisition/analytic.py`, the `LogNoisyExpectedImprovement` and `NoisyExpectedImprovement` use the function `_get_noiseless_fantasy_model` in order to repeatedly sample from fantasy model. But `_get_noiseless_fantasy_model` only works for default GP (i.e. with default Matern kernel) & also with no input or outcome transforms.
I think that it would make sense if this code were written to work with any kind of `SingleTaskGP`, not just the default one with no input and outcome transforms.

## To reproduce

Setup code:
```python
import torch
from botorch.models.gp_regression import SingleTaskGP
from botorch.models.transforms.outcome import Standardize
from botorch.models.transforms.input import Normalize
from botorch.acquisition.analytic import LogNoisyExpectedImprovement
from gpytorch.kernels import ScaleKernel, RBFKernel
train_X = torch.rand(10, 2, dtype=torch.float64) * 2.3 - 4.9
train_Y = torch.sin(train_X).sum(dim=1, keepdim=True) * 3. + 2.
train_Yvar = torch.full_like(train_Y, 1e-3)
```

Now, say we do,
```python
model = SingleTaskGP(
     train_X, train_Y,
     outcome_transform=Standardize(m=1),
     input_transform=Normalize(d=2),
     train_Yvar=train_Yvar)
LogNEI = LogNoisyExpectedImprovement(model, train_X)
```
then this is the output:
```
Traceback (most recent call last):
  File "/Users/aloja/Library/Mobile Documents/com~apple~CloudDocs/cornell/RESEARCH/BayesOpt/CODE/botorch/alon_test.py", line 139, in <module>
    LogNEI = LogNoisyExpectedImprovement(model, train_X)
  File "/Users/aloja/Library/Mobile Documents/com~apple~CloudDocs/cornell/RESEARCH/BayesOpt/CODE/botorch/botorch/acquisition/analytic.py", line 634, in __init__
    fantasy_model = _get_noiseless_fantasy_model(
  File "/Users/aloja/Library/Mobile Documents/com~apple~CloudDocs/cornell/RESEARCH/BayesOpt/CODE/botorch/botorch/acquisition/analytic.py", line 1088, in _get_noiseless_fantasy_model
    fantasy_model.load_state_dict(state_dict)
  File "/Users/aloja/opt/anaconda3/envs/botorch-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SingleTaskGP:
	Unexpected key(s) in state_dict: "outcome_transform.means", "outcome_transform.stdvs", "outcome_transform._stdvs_sq", "outcome_transform._is_trained", "input_transform._coefficient", "input_transform._offset".
```

And if we do,
```python
model = SingleTaskGP(
     train_X, train_Y,
     covar_module=ScaleKernel(RBFKernel(ard_num_dims=train_X.shape[-1])),
     train_Yvar=train_Yvar)
LogNEI = LogNoisyExpectedImprovement(model, train_X)
```
then the output is:
```
Traceback (most recent call last):
  File "/Users/aloja/Library/Mobile Documents/com~apple~CloudDocs/cornell/RESEARCH/BayesOpt/CODE/botorch/alon_test.py", line 137, in <module>
    LogNEI = LogNoisyExpectedImprovement(model, train_X)
  File "/Users/aloja/Library/Mobile Documents/com~apple~CloudDocs/cornell/RESEARCH/BayesOpt/CODE/botorch/botorch/acquisition/analytic.py", line 634, in __init__
    fantasy_model = _get_noiseless_fantasy_model(
  File "/Users/aloja/Library/Mobile Documents/com~apple~CloudDocs/cornell/RESEARCH/BayesOpt/CODE/botorch/botorch/acquisition/analytic.py", line 1088, in _get_noiseless_fantasy_model
    fantasy_model.load_state_dict(state_dict)
  File "/Users/aloja/opt/anaconda3/envs/botorch-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SingleTaskGP:
	Missing key(s) in state_dict: "covar_module.base_kernel.lengthscale_prior.concentration", "covar_module.base_kernel.lengthscale_prior.rate", "covar_module.outputscale_prior.concentration", "covar_module.outputscale_prior.rate".
```

## Expected Behavior
The code should run correctly without any errors.

## System information

**Please complete the following information:**
- BoTorch Version: 0.1.dev1915+g0455dc3
- GPyTorch Version: 1.12
- PyTorch Version: 2.2.2
- Computer OS: MacOS Monterey

## Additional context

Currently the code is --
```python
# initialize a copy of SingleTaskGP on the original training inputs
# this makes SingleTaskGP a non-batch GP, so that the same hyperparameters
# are used across all batches (by default, a GP with batched training data
# uses independent hyperparameters for each batch).
fantasy_model = SingleTaskGP(
    train_X=model.train_inputs[0],
    train_Y=model.train_targets.unsqueeze(-1),
    train_Yvar=model.likelihood.noise_covar.noise.unsqueeze(-1),
)
# update training inputs/targets to be batch mode fantasies
fantasy_model.set_train_data(
    inputs=batch_X_observed, targets=Y_fantasized, strict=False
)
# use noiseless fantasies
fantasy_model.likelihood.noise_covar.noise = torch.full_like(Y_fantasized, 1e-7)
# load hyperparameters from original model
state_dict = deepcopy(model.state_dict())
fantasy_model.load_state_dict(state_dict)
return fantasy_model
```

I think the code should instead something along the lines of the following:

```python
outcome_transform = deepcopy(getattr(model, "outcome_transform", None))
# initialize a copy of SingleTaskGP on the original training inputs
# this makes SingleTaskGP a non-batch GP, so that the same hyperparameters
# are used across all batches (by default, a GP with batched training data
# uses independent hyperparameters for each batch).
fantasy_model = SingleTaskGP(
    train_X=model.train_inputs[0],
    train_Y=model.train_targets.unsqueeze(-1),
    train_Yvar=model.likelihood.noise_covar.noise.unsqueeze(-1),
    covar_module=deepcopy(model.covar_module),
    mean_module=deepcopy(model.mean_module),
    outcome_transform=outcome_transform,
    input_transform=deepcopy(getattr(model, "input_transform", None))
)

if outcome_transform is not None:
    outcome_transform.means = outcome_transform.means.expand(batch_X_observed.size(0), *outcome_transform.means.shape)
    outcome_transform.stdvs = outcome_transform.stdvs.expand(batch_X_observed.size(0), *outcome_transform.stdvs.shape)
    outcome_transform._stdvs_sq = outcome_transform._stdvs_sq.expand(batch_X_observed.size(0), *outcome_transform._stdvs_sq.shape)

Yvar = torch.full_like(Y_fantasized, 1e-7)
# Need to transform the outcome just as in the SingleTaskGP constructor.
if outcome_transform is not None:
    # Need to unsqueeze for BoTorch and then squeeze again for GPyTorch
    Y_fantasized, Yvar = outcome_transform(Y_fantasized.unsqueeze(-1), Yvar.unsqueeze(-1))
    Y_fantasized = Y_fantasized.squeeze(-1)
    Yvar = Yvar.squeeze(-1)

# update training inputs/targets to be batch mode fantasies
fantasy_model.set_train_data(
    inputs=batch_X_observed, targets=Y_fantasized, strict=False
)
# use noiseless fantasies
fantasy_model.likelihood.noise_covar.noise = Yvar

# This calls _set_transformed_inputs
# Need to do this AFTER setting all the data
# so that the input data is transformed
# Probably don't actually need to do this here though.
fantasy_model.eval()

return fantasy_model
```

I coded this, and tried to make it pass all the unit tests. It did pass all the unit tests (the ones in `test/acquisition/test_analytic.py` in `TestNoisyExpectedImprovement`) how they are now, but then I decided that it would be a good idea to add more unit tests to test this new functionality (the ability to retain the same input and outcome transform, and other covar module and mean module, etc.)
(Note -- in `_get_model`, I needed to `model.load_state_dict(state_dict, strict=False)` set `strict=False`.)
When I did this, then it didn't pass all the unit tests, e.g., the `self.assertGreater(val[0].item(), 8e-5)`
            `self.assertLess(val[1].item(), 1e-6)` and `self.assertAllClose(X_test.grad[0], X_test_log.grad[0], atol=atol, rtol=rtol)` did not always pass.
So I think that either there is something subtle that is going wrong with the code, or the unit tests need to be changed more cleverly to adapt to the different settings...

Thanks!

**Comment by sdaulton** [comment]
Thanks for raising this issue. We should definitely support more general models for the analytic (Log)NoisyExpectedImprovement acquisition functions. Regarding your code and unit test issues: could you open a draft PR to make it easier to discuss/review?

**Comment by 71c** [comment]
Yes, I'll do that!

So you're saying that it is OK if the tests don't all pass and I'm not completely sure if the code is 100% correct, and I can submit a pull request as a draft. The reason why I didn't just make a pull request directly is because I thought that they needed to be complete/perfect.

**Comment by sdaulton** [comment]
A draft is fine! That will make it easier to review the changes and understand what tests are failing. Thanks!

**Comment by saitcakmak** [comment]
This was fixed in https://github.com/pytorch/botorch/pull/2414. Thanks for the PR!
