### ISSUE TITLE
[Bug] AttributeError: 'SimpleCustomGP' object has no attribute 'num_outputs'

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#354]
# 🐛 Bug
As I was trying to run [the first code example](https://botorch.org/tutorials/custom_botorch_model_in_ax) in the tutorial (using botorch with ax), I got an error AttributeError: 'SimpleCustomGP' object has no attribute 'num_outputs'. Could anyone explain to me why this would happen?

Here's my versions of dependencies:
python 3.7.4
gpytorch 1.0.4
scipy

** Stack trace/error message **
Running optimization batch 1/5...
Traceback (most recent call last):
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 342, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'SimpleCustomGP' object has no attribute '_num_outputs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 342, in __getattr__
    return super().__getattribute__(name)
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/botorch/models/gpytorch.py", line 102, in num_outputs
    return self._num_outputs
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 344, in __getattr__
    raise e
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 339, in __getattr__
    return super().__getattr__(name)
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'SimpleCustomGP' object has no attribute '_num_outputs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bo_ax.py", line 84, in <module>
    batch = exp.new_trial(generator_run=model.gen(1))
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/ax/modelbridge/base.py", line 609, in gen
    model_gen_options=model_gen_options,
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/ax/modelbridge/array.py", line 212, in _gen
    target_fidelities=target_fidelities,
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/ax/modelbridge/torch.py", line 214, in _model_gen
    target_fidelities=target_fidelities,
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/ax/models/torch/botorch.py", line 334, in gen
    outcome_constraints=outcome_constraints,
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/ax/models/torch/utils.py", line 178, in subset_model
    if len(idcs) == model.num_outputs:
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 344, in __getattr__
    raise e
  File "/home/aleczshi/anaconda3/lib/python3.7/site-packages/gpytorch/module.py", line 339, in __getattr__
    return super().__getattr__(name)

**Comment by Balandat** [comment]
Thanks for flagging this, we added the `num_outputs` property to the model API (see [here](https://github.com/pytorch/botorch/blob/master/botorch/models/model.py#L52-L56)) in order to reduce ambiguity / improve error messages, must have missed updating the tutorial for this change. I'll put up a fix shortly. 

Since this is a `GPyTorchModel` with a single output, all you should need to do to fix this is give the model a `_num_outputs` attribute, i.e. 
```
class SimpleCustomGP(ExactGP, GPyTorchModel):
    
    self._num_outputs = 1

    def __init__(self, train_X, train_Y):
        [...]
```
