### ISSUE TITLE
[question] The training method of multi-Task model

### ISSUE THREAD

**Issue by zhaojingyao** [pytorch/botorch#521]
Hi,

I would like to ask why in gpytorch, the multi-task model stipulates that train_X for different tasks is the same, and the number of training samples for different tasks is also the same. I can understand this rule because it is in line with the multi-task Gaussian process training method That I learned about in Bonilla's paper.

But why is there no need to follow this rule in BOtorch?  Is it because botorch's estimation of hyperparameters is not a way of using the maximized likelihood function? It works well even when I use completely different samples.

**Comment by danielrjiang** [comment]
Hi @zhaojingyao, you can take a look at the example code in the docstring of the `MultiTaskGP` class (https://github.com/pytorch/botorch/blob/master/botorch/models/multitask.py) to see an example of how to use task indices to specify which task each training point of `train_X` belongs to. Note that this example shows 10 training points for the first task and 20 (different) training points for the second task.

**Comment by zhaojingyao** [comment]
Thanks for your reply. 

I have another question to ask you. While I was training the MultiTaskGP model, the 'RuntimeError: cholesky_cpu: U(159,159) is zero, singular U' error is likely to occur when the data set is large.

Below is the complete error message:

Traceback (most recent call last):

  File "<ipython-input-606-33b2813a4542>", line 1, in <module>
    runfile('D:/multi-task/mi/MT/mt.py', wdir='D:/multi-task/mi/MT')

  File "C:\Users\zjy\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/multi-task/mi/MT/mt.py", line 224, in <module>
    posterior = model.posterior(test_x)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\botorch-0.3.0-py3.7.egg\botorch\models\gpytorch.py", line 586, in posterior
    mvn = self(X_full)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\models\exact_gp.py", line 328, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\models\exact_prediction_strategies.py", line 321, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\models\exact_prediction_strategies.py", line 339, in exact_predictive_mean
    res = (test_train_covar @ self.mean_cache.unsqueeze(-1)).squeeze(-1)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\utils\memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\models\exact_prediction_strategies.py", line 288, in mean_cache
    mean_cache = train_train_covar.inv_matmul(train_labels_offset).squeeze(-1)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\lazy\lazy_tensor.py", line 959, in inv_matmul
    return func.apply(self.representation_tree(), False, right_tensor, *self.representation())

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\functions\_inv_matmul.py", line 47, in forward
    solves = _solve(lazy_tsr, right_tensor)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\functions\_inv_matmul.py", line 11, in _solve
    return lazy_tsr._cholesky()._cholesky_solve(rhs)

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\utils\memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\lazy\lazy_tensor.py", line 415, in _cholesky
    cholesky = psd_safe_cholesky(evaluated_mat, jitter=settings.cholesky_jitter.value()).contiguous()

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\utils\cholesky.py", line 50, in psd_safe_cholesky
    raise e

  File "C:\Users\zjy\Anaconda3\lib\site-packages\gpytorch-1.1.1-py3.7.egg\gpytorch\utils\cholesky.py", line 27, in psd_safe_cholesky
    L = torch.cholesky(A, upper=upper, out=out)

RuntimeError: cholesky_cpu: U(117,117) is zero, singular U.

It looks like something wrong in prediction...

**Comment by zhaojingyao** [comment]
![image](https://user-images.githubusercontent.com/40418158/91152730-eca58a00-e6f1-11ea-90a3-34230a66789a.png)

The formula for MML is shown in the figure above. For MultiTaskGP , the dimension of K is N*M, so the dimension of y should also be N*M, but according to the rules of BOtorch, the dimension of the target vector is not necessarily N*M.

**Comment by Balandat** [comment]
This is due to numerical issues that can occur when the covariance matrices are near singular. We adaptively add jitter in gpytorch, but seems to not be enough in this case (which is surprising). Would you be able to share the data set that you're using for this so we can take a closer look?

**Comment by zhaojingyao** [comment]
> This is due to numerical issues that can occur when the covariance matrices are near singular. We adaptively add jitter in gpytorch, but seems to not be enough in this case (which is surprising). Would you be able to share the data set that you're using for this so we can take a closer look?

Here is my code. I set a seed to make sure the same training set is generated each time. I've found that not every run will go wrong, and you may need to run it more than once(about ten times maybe...). 

[mt.txt](https://github.com/pytorch/botorch/files/5146663/mt.txt)


                    
                
Another problem is that when the training sample is large, the predictive variance of the model in some areas is very strange.
![image](https://user-images.githubusercontent.com/40418158/91657111-219a4e00-eaf1-11ea-9973-e78b99b0e633.png)

And here is prediction of single-GP:
 
![image](https://user-images.githubusercontent.com/40418158/91657127-4098e000-eaf1-11ea-9a1f-f73225102015.png)

**Comment by Balandat** [comment]
Which version are you running this on? I fixed a MTGP bug in https://github.com/pytorch/botorch/pull/485 that hasn't made it into a release yet - that could explain the weirdness in the results that you're seeing. Can you try using the current master?

**Comment by zhaojingyao** [comment]
I tried to install the latest version of the BoTorch, but it still had this problem。

**Comment by Balandat** [comment]
Did you use the latest version at the time or install from the master branch (would have had to been the latter to get the fix)? This should have been fixed since then, feel free to re-open if you still have this issue.
