### ISSUE TITLE
ModuleNotFoundError and double print

### ISSUE THREAD

**Issue by JoergFranke** [pytorch/botorch#826]
I can't use Botorch due to a ModuleNotFoundError. I started with a new conda env, installed botorch via `conda install botorch -c pytorch -c gpytorch` and run the first code section in this tutorial: https://botorch.org/tutorials/custom_botorch_model_in_ax.

I receive  the following error:
```
Traceback (most recent call last):
  File "/home/user/workspace/python/development/botorch.py", line 13, in <module>
    from botorch.models.gpytorch import GPyTorchModel
  File "/home/user/workspace/python/development/botorch.py", line 13, in <module>
    from botorch.models.gpytorch import GPyTorchModel
ModuleNotFoundError: No module named 'botorch.models'; 'botorch' is not a package
```

The weird part is I run a script that contains only:
 ```
print("Hello")
from botorch.models.gpytorch import GPyTorchModel
```
it outputs:
```
Hello
Hello
Traceback (most recent call last):
  File "/home/user/workspace/python/development/botorch.py", line 13, in <module>
    from botorch.models.gpytorch import GPyTorchModel
  File "/home/user/workspace/python/development/botorch.py", line 13, in <module>
    from botorch.models.gpytorch import GPyTorchModel
ModuleNotFoundError: No module named 'botorch.models'; 'botorch' is not a package
```

Why does it print "Hello" twice?

I tested it on Ubuntu 20.04 with Python 3.8.10 and botorch version 0.1.4, 0.2.0 and 0.4.0. 
Please find the environment below.

```
channels:
  - gpytorch
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - botorch=0.4.0=0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.68.2=h36276a3_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gpytorch=1.4.2=0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.2.0=h06a4308_610
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.2=py38h2d18471_0
  - numpy-base=1.20.2=py38hfae3a4d_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - pandas=1.2.4=py38h2531618_0
  - pcre=8.44=he6710b0_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.1.1=py38h06a4308_0
  - pyaml=20.4.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.10=hdb3f193_7
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py38h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy=1.6.2=py38had2a1c9_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu111
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
```

**Comment by Balandat** [comment]
Hmm this seems odd, certainly `botorch` should be a package in the environment. Did you verify that the way you run your script indeed makes sure this is run in the new environment (which looks good from the deps btw)? Maybe just run `import sys; print(sys.version)` prior to the botorch import?

**Comment by JoergFranke** [comment]
Thanks for your answer. Now, I first import sys and print the version, but the effect is the same. 
Assume the two file attached in one folder and no conda env named test so far.
The output after creating a new env 
```
conda env create -f environment.yml
conda activate test
python botorch.py
```
and running the script is:

```
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] on linux
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] on linux
botorch import
Traceback (most recent call last):
  File "botorch.py", line 3, in <module>
    import botorch
  File "/home/user/workspace/python/tmp/botorch.py", line 5, in <module>
    from botorch.models.gpytorch import GPyTorchModel
ModuleNotFoundError: No module named 'botorch.models'; 'botorch' is not a package
```

The botorch.py script contains:
```
import sys
print('Python %s on %s' % (sys.version, sys.platform))
import botorch
print("botorch import")
from botorch.models.gpytorch import GPyTorchModel
```

The envrionment.yml contains:
```
name: test
channels:
  - gpytorch
  - nvidia
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - botorch=0.4.0=0
  - bzip2=1.0.8=h7b6447c_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.68.2=h36276a3_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gpytorch=1.4.2=0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.2.0=h06a4308_610
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.2=py38h2d18471_0
  - numpy-base=1.20.2=py38hfae3a4d_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - pandas=1.2.4=py38h2531618_0
  - pcre=8.44=he6710b0_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.1.1=py38h06a4308_0
  - pyaml=20.4.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.10=hdb3f193_7
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py38h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy=1.6.2=py38had2a1c9_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu111
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
 ```

When I comment out the line `from botorch.models.gpytorch import GPyTorchModel` I get:
```
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] on linux
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] on linux
botorch import
botorch import
```

Still a somehow weird double print.

**Comment by ferreirafabio** [comment]
I was able to reproduce the same exact anomaly with the given files in a freshly created environment under conda version 4.10.1.

**Comment by Balandat** [comment]
> I was able to reproduce the same exact anomaly with the given files in a freshly created environment under conda version 4.10.1.

Was this on a linux setup as well?

**Comment by ferreirafabio** [comment]
Yes, also on Ubuntu 20.04

**Comment by Balandat** [comment]
Let me try to repro this in a VM setup.

**Comment by saitcakmak** [comment]
I tried this on Ubuntu 20.04 using Conda 4.9.2 and Python 3.9.5. On a clean environment, I did `conda install botorch -c pytorch -c gpytorch` and ran a file containing `from botorch.models.gpytorch import GPyTorchModel` without any issues.

**Comment by Balandat** [comment]
Can you try renaming the `botorch.py` file into something else? This probably clobbers the botorch library module if you run this from the same dir.

**Comment by Balandat** [comment]
This would also be consistent with the double print: 
`python botorch.py` runs the file and prints the first line `print("Hello")`, then `from botorch.models.gpytorch import GPyTorchModel` tries to import `botorch.py` and again prints that first line before realizing that that file is not a module.

**Comment by JoergFranke** [comment]
That's the solution, thanks a lot!
